### ISSUE TITLE
protobuf on OSX - brew newer version updated to 3.x - 2.x not available

### ISSUE THREAD

**Issue by jguitton** [namecoin/namecoin-core#103]
`./qt/paymentrequest.pb.h:17:2: error: This file was generated by an older version of protoc which is
# error This file was generated by an older version of protoc which is

 ^
./qt/paymentrequest.pb.h:18:2: error: incompatible with your Protocol Buffer headers. Please
# error incompatible with your Protocol Buffer headers.  Please

 ^
./qt/paymentrequest.pb.h:19:2: error: regenerate this file with a newer version of protoc.
# error regenerate this file with a newer version of protoc.

 ^`

**Comment by jguitton** [comment]
do a
`brew tap homebrew/versions`
then
`brew unlink protobuf`
and
`brew install protobuf260`

you can run namecoin again

build:
`git reset --hard
./autogen.sh
./configure
make`

**Comment by domob1812** [comment]
Closing this, as it is likely outdated (and perhaps actually fixed by #67?).  Feel free to reopen if still relevant.
