### ISSUE TITLE
Merge commits aren't signed

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#107]
I notice that several of the most recent merge commits, e.g. 7aeafb672ec4c3bf8620a0db8b98aab973923693 , fdfb20fc263a72acc2a3c460b56b64245c1bedcb , and 9f71f45fbc2b9e1c3a3f2a1fc856967426dc6d5a aren't PGP-signed.  For future reference, merge commits should be PGP-signed; it can be automated via the `github-merge.py` script (documentation is at https://github.com/namecoin/namecoin-core/tree/dev/contrib/devtools#github-mergepy ).

Cheers.

**Comment by domob1812** [comment]
f04e1386d4231870fc146e9e5b3130f7aba14a8f was created using Bitcoin's `github-merge.py` script.  I'll use it in the future for all merges of pull requests.
