### ISSUE TITLE
ERROR: CheckDbLockLimit : 4503 locks estimated, that is too much for BDB

### ISSUE THREAD

**Issue by bitkevin** [namecoin/namecoin-core#114]
```
3 locks estimated, that is too much for BDB
2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks estimated, that is too much for BDB
2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks estimated, that is too much for BDB
2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks estimated, that is too much for BDB
2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks estimated, that is too much for BDB
2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks estimated, that is too much for BDB
2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks estimated, that is too much for BDB
2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks estimated, that is too much for BDB
2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks estimated, that is too much for BDB
2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks estimated, that is too much for BDB
2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks estimated, that is too much for BDB
2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks estimated, that is too much for BDB
```

```
$ uname -a
Linux fa81a9409b16 3.13.0-86-generic #130-Ubuntu SMP Mon Apr 18 18:27:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

I use Docker to run namecoind-v0.13.0rc1, here is the `Dockerfile`:
https://github.com/btccom/btcpool/blob/master/docker/namecoind/v0.13.0rc1/Dockerfile

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

kevin:
> ``` 3 locks estimated, that is too much for BDB 2016-11-07 15:26:45
> ERROR: CheckDbLockLimit : 4503 locks estimated, that is too much
> for BDB 2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks
> estimated, that is too much for BDB 2016-11-07 15:26:45 ERROR:
> CheckDbLockLimit : 4503 locks estimated, that is too much for BDB 
> 2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks estimated,
> that is too much for BDB 2016-11-07 15:26:45 ERROR:
> CheckDbLockLimit : 4503 locks estimated, that is too much for BDB 
> 2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks estimated,
> that is too much for BDB 2016-11-07 15:26:45 ERROR:
> CheckDbLockLimit : 4503 locks estimated, that is too much for BDB 
> 2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks estimated,
> that is too much for BDB 2016-11-07 15:26:45 ERROR:
> CheckDbLockLimit : 4503 locks estimated, that is too much for BDB 
> 2016-11-07 15:26:45 ERROR: CheckDbLockLimit : 4503 locks estimated,
> that is too much for BDB 2016-11-07 15:26:45 ERROR:
> CheckDbLockLimit : 4503 locks estimated, that is too much for BDB 
> ```
> 
> ``` $ uname -a Linux fa81a9409b16 3.13.0-86-generic #130-Ubuntu SMP
> Mon Apr 18 18:27:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux ```
> 
> I use Docker to run namecoind-v0.13.0rc1, here is the
> `Dockerfile`: 
> https://github.com/btccom/btcpool/blob/master/docker/namecoind/v0.13.0rc1/Dockerfile
>
> 
> 

In what context are you getting this error?  While syncing?  While
mining?  Something else?

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYIKLcAAoJELPy0WV4bWVwT34P/1QpEl4ITfFkkLmY1fD5O0N1
U1Rxr3deNfeHBcsJLrb16o/V6cSvA4G0fhFoZ/NW/i9SZFt0HIv12Q29K17kOCwz
bggtmaPbeElqgI8sHl2ZlxSmN6RrnDykdyTi4iSY9c4ng8p+j3c1ujgLIum98Sew
QGjmkc+RUr6ukRAHJxI+IyadDYkmwZv3l1eleflZD7ghQIB8IJPmxjaFyccHRvxH
BuJQK4wTRd2glHoah5lnOBt+xSaqR1uW+6s86SV06YXUR3vgd9mMj0kifGdCx7tQ
gRKuu/dzmmhxG35cCCxAh5kWHfmdd9r+fK/hntgsDXswj+EmRWXF2aILmM5mogzB
WSr0Z+UYk+0xSt9BrPxRKsDxsUoorhyjEvoZkMYRYFhARYzZMIzd5Q8Qeu5py06H
2alYP7vdfpe+VMsAcErjoNT8Wnvlx0Q/x62447YwGxhTOM4V6lZE9IydInD+cDVU
KZmFy/HaqFXm/K3Xq5f/gL9mw4p0kXRItw+rIdHgSgktP3jUuoFLnQkjxlPaclrA
5uG+JEAedwr/Kx3VUCTd03dOs7Eu1jY5WtSpHOWJyjpp6cmfnM9x8ckEDkI7TOuH
DZbWS/fhddW7fTyW+yzax7A8B6wt4cDo1ZveZeQ9IydZgh+8c6hFfualhCefkmnk
TX90xQoPbrcrV5K71eYV
=nT1r
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I'm not seeing this error in my debug.log on a
nc0.13.99-name-tab-beta1 node on x86_64 GNU/Linux.  (I just let it
sync up the last 4 days or so.)
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYIKTfAAoJELPy0WV4bWVwVG8P/3IxZi5twOqZEEh9rAom2BCe
B63/YCYziqPddfEk3LSmvrpCAS8OdAyICGc3J8beEW7lhocWKsAdA7PlVdxfBnGJ
QlOxeBXGRDtXebLHaGWYBEKAjA0wdCiPYJRVX+/Qp5lsJuvf3S0c6IDupSyx1WT5
3fFFP9mpk1a2EDPyOEP+QStUWnMbMp3DTU+OvjTMkugVaFzx8TxlyrapJIC+6NAv
77ps5wz1YGQBzfbKrSmmfl6N/KVngFg1vlfQDDMPydQYE6le5xpxLF9NgqP7/Knr
t2PWCrpG3w3hXk2je3itV2CdPRacMV8ECxogOH2FMMhe3V2N8ReTuUuSYkabU+zK
Zcr3aCSbdmx/m0v1yGgEimhfgxNTAAmofFs6NN88DWJGQXZv4ORFV+sdXWMdBjrU
IBzxUFFUMlYGJuKQl2Ks1WN5UZQb5sxljOmT9ZtHAYPFv8b5r9LghJnYsqUVcMlw
wPhB72TBDQAkOqXCsc72EB7FGDpsRzboWrFX8Jmn3XvIEBWwz4InVBA9ZbHqjOJ1
06/mfDjpNz+VCQKjBbl40FoB+uUCqZruPEsAPep+G9Zl+uCaQBTo+E1OmA27XSX4
BdX6atTrOf3R90C8zngsIjujQsbseOmThLKCzu13ublwrfFRLVA1i7RxgPiaVl5l
IL3dP4SkBPWhKG55tH0R
=iZjE
-----END PGP SIGNATURE-----

**Comment by bitkevin** [comment]
> In what context are you getting this error?  While syncing?  While
 > mining?  Something else?

I use namecoind for merged mining, call several rpc commands such like `getauxblock`, `getinfo`. The merged mining thread will call `getauxblock` about every 10 seconds.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

kevin:
> I use namecoind for merged mining, call several rpc commands such 
> like `getauxblock`, `getinfo`. The merged mining thread will call 
> `getauxblock` about every 10 seconds.

Does merged mining still work okay when this shows up in the logs?
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYILnuAAoJELPy0WV4bWVw6yMP/RTf6CYnt3/UaIY6/LRsG10C
UojC7WIt1H9ln+3L3tGE9902f16vQcVUp2qGboMcPCmpuMqbG+aeRNw8LMYYyVtC
7OztJNS8gX9hUg41RNgcUwmxVfdCMFEAC3+fsA1gO4D2zPAb5fOuQZcemkhQMmsn
NeVYcbNTGulAxpt/Gfzlq8Bk+R9dHbmlnyRwYYFNtiJH1J9ZwXYZs+6wMBCRjTE7
7Tpyl8TbcWouPmoeEXxyO/ug/NxioatzrGWkEfo53mruzUHP6ixDN1PbF81I5cyQ
u3GSg0WETciQtdxKgmVYngrRCQjR+ti5Hf1QYpHIjbS3Or4TTcC6UOzRi81COFSW
/TbQuAjYZk5+/1vurbkk5Qjhna+bvzrA5CJ5syrjSteTyGJm6+/IygLx23pai25R
i7Q+Y0uZGFaq1+NxopxhuLzGOFWHHEoOb94r5EU3BHUvcQW+PjeRW87o6BcTHl9F
1fBTMPEcD45lAnPhLT0F1cQjYYc7plEqQlLdX2uPVseSYlDlmu+C3W4+kVBsqRaw
K0EJ5IDJ59LjNl+xuIJ9eXGC8GPZVO8mKQ1wj46jU3xvwfv8/jNnM7WklWAaaVnY
jEChdZguN8HtkKmrsTjl05Y428ntRh1QqwXzbzrrtpGgYahvXP8AFrk4CuCi5sX6
gWusPbD2Cx4Ahx8qhoum
=b31U
-----END PGP SIGNATURE-----

**Comment by bitkevin** [comment]
> Does merged mining still work okay when this shows up in the logs?

No. Can't call RPC anymore, Hanged. So I have to kill the process and restart namecoind.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

kevin:
>> Does merged mining still work okay when this shows up in the
>> logs?
> 
> No. Can't call RPC anymore, Hanged. So I have to kill the process
> and restart namecoind.

@domob1812 , any ideas on this?

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYIzu1AAoJELPy0WV4bWVwNrMP/A3y5+JoUHFdRYaa6UfA+C7L
6x9T10AIalyqpQKEAb8of/nVnA0ZYGdlB0uExb7oaamwAFEM/nVHmiIpAUjSOVcp
ImlbL0ktXPHbPE6XPZxCUS0vp9j/Qw3uNXPwcHGMmfnZsV+Hp2mA21gUCqffH3df
VWJgCrmbLGgt40c/AH4t4Is1WDrq0wxivPwcKU/JPh57sG8xdpN/OVox9Tn3CMmB
v4ATgZTTa/xx9QLALQA5C1wQfgVd6tPG6pb1fcp9qE8VUBjm6XJN4JKfF9A5eMv8
VYK6UQTX2xUAE/gIwmqh6YBe+yaf0vWw+x7aNKYomRytEFqZE2TXSp3znD+oPNvM
ygx2Z/w0ruScqQ0hfkrfptdL4UlTTPESaPpYV4h2heJqTjXFb286xeTyA/cZA88A
GCF0yASfrHP1Ui6I2UeEEQBIC2rpe2FT5IKCurdWhXfoG8Zu9a3US/NnnPXARq/4
NU1HR8huY0MVuhkS+0jf7X4/umqVEO2MUQB5BcdwH6yXu0xb8hOyxfOOzdlkDhLs
OA8/q2fTnm0ycJ8pLSdJ4o2V6pb7gYg8Kzyjj1/gjhxM7ivpbLEr+ZGRU6icEbNY
fgDD1ZB1CC+2M5dXKYPMHIdWoB97hir91UItg8RmE77RA85wfGO7V+1VgE7uREhy
51lubia3z7ODWFszDi+j
=ChiF
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
Not sure.  The code to create a block (in `src/miner.cpp`) is supposed to check the lock limit when adding transactions, but there could of course be a bug in it.  Can you consistently reproduce this?

**Comment by bitkevin** [comment]
@domob1812 I think it's hard to reproduce this. I run 4 namecoind nodes for 2 months, all of them are for merged mining, only happened once.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

@domob1812 Do our automated tests check whether the mining code has
the correct behavior when a block is attempted to be mined that
exceeds the BDB lock limit?
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYJnO8AAoJELPy0WV4bWVwVX8P/R73anI9zGqm9DDzUPB6bakH
f5ii7oLowDiBpeeFMmPfD0rTpgcB3SWctq593DMrLnXaC9C6/wEVAkmRgIbCh7u9
GnenQf7ezHHWCKja7FrVVZE6UxAB1P33R920H6qK+7jZItG/KvG/lYIsikp9pCe5
1PMEAycof85J6fpamoQgcicGWkqYsCZaEZC6VeROOsSiOS6vGmb2guK+jhZ9PtLt
Gl+s/KMEo367kF3rCgJxqone68VsDrLr/j5jCjEbK1CC5oAEKt2r2vOd/I4Vik1T
DY0hA63LQPCxswwIHbGql3/Us778NeXaxveF1pvB3EKs4wytihOeXrz4yvjkXtQP
U3f0zAmAD64cd7W7WPjMUYdZlyNzTIvUAEYHXtH/8te1oDgiKpEotT/jqkzQSPBr
byFo6YH7VfhpXejf5/yBIi+Ke5tuHWYkytmY+JYHDRcFHNxLFjBK1QCbYX9R+C49
F5EkxMiZ5q8kpkOXy9sTnhAefx80yhT8Boo2luL3+lClkiDXxm+OpRjOEaFCiN5R
fo/GkRAkxM4sWiA1YOD8R1ubT6fd4RcMeKpIfZAha13cn1x4pNnwoap4osfgV81+
36vZqCDIa00wtWipSgQn5Ww45ETiUrOAIPa7eh3ethrhEqudEWmzvA8COJIPk75V
WBzu39s057dTBTbKcPw/
=UCYH
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

@domob1812 Bump.
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYMYiAAAoJELPy0WV4bWVwO2UQALsYw8iObqVLhzwQN7UbGwsI
sVZMID9PktQvKvdM0Fc0NLqfu5ADnQtF87hFXkpnsnBgzE172fva0uy+tvLtayAr
U6biZSjllJCXCv48d9/RfUVE4IWWxlwNENS2bO0GbYWkjSpulwkRSQ7CQn88MWsi
wSgZG+yv/4+GpavmkJ62JkznUkOqhTxV1C4dtTfxkY84gDyrFY/ox1/0fjurAzHw
xk9RTjzxKt4twiZAy7ofJB8mLUgX6C1nxgWuJnqf97sHoANBHI23E/hfxFCruZUV
o5eBfUu0fw2kjom/7cXvGXM+r9y7X0EMB1gATgM2JWUZKWUjIzBLi5mNkjpLjKmQ
jp3r0iaTsQHAuTSP9KY4RdMJAMD6ivw5GWAPD5Aj5K6yrd0SLDHHtF8u+H4Ewa+g
ArXDPRPo3ZodpTFSVqtWtKKdW69zrgqRoq6wtQ4FXshTFljFjqzHZbu92p6sFZDx
OzfKEtf2WUIss1VXw7VC/97LoOXWNQYYCcrSIBLsZSqQGJnbrJONuRRYD9tJSF3z
tUuOy/kBXJbZtTNQZfbpKnHyVk/8LGu8BOFhYtKnuaxXZ75rh0wGxKpm8qPLPHcE
sl12TfHTvVAgFfM2OU1UWzJNzVbcDHyk80Uxh3ShMAiAXnRJr4tCKRX9ylGrbdZo
bv4HF0VVHadTXVARTood
=88qQ
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
I don't think we have any regression test for that.  It would probably be expensive to do this, as you have to create a lot of inputs and then spend all of them in a block.  I think we should try to finally get rid of the limit with the planned fork, rather than spend a lot of effort to keep it.

**Comment by domob1812** [comment]
Closing for now.  Feel free to reopen if this issue still persists and can be reproduced for debugging.
