### ISSUE TITLE
Core 0.13.99 crashes on broadcast of invalid multiple-name-update transaction.

### ISSUE THREAD

**Issue by maxweisspoker** [namecoin/namecoin-core#116]
Edit:  Reddit post:  https://www.reddit.com/r/Namecoin/comments/5epqf4/trouble_sending_raw_transaction/

Hello, I have an invalid transaction which crashes the client.  It is only invalid because it attempts to do multiple name updates at once.  Other than that it is a valid and good transaction.  The client happily signs it, and "decoderawtransaction" decodes it so I can view it.  However, when I attempt to broadcast the transaction, the client immediately crashes.  When running namecoind and issuing the command via the namecoin-cli app, about half the time it's able to spit out the following error:

namecoind: txmempool.cpp:58: CTxMemPoolEntry::CTxMemPoolEntry(const CTransaction&, const CAmount&, int64_t, double, unsigned int, bool, CAmount, bool, int64_t, LockPoints): Assertion `!nameOp.isNameOp()' failed.

Then the client crashes.  The debug log file is not updated with any relevant info prior to the crash.

This has happened in two different versions of Namecoin Core 0.13.99.  One is on my desktop computer, which was build from source using commit b19c20b5ff61472a195832cb6f34eda9f5707f90 in order to get the name management GUI.  And the other is on my server, which was built from source using whatever the latest github had a few months ago.  I deleted the source folder and don't know how to query the application itself for its exact build.  (It's cli only, no gui.)  But the version is 0.13.99.  My desktop OS is Mint 18 based on Ubuntu 16.04, and my server is Ubuntu Server 16.04.

Here is the offending transaction:

0071000004232b3e1b869ce9460de11a990e2d210c869242f09f48b603b50f122797cb966d000000006b483045022100d0c192140f7aae6878f9baf8505717da80adb1634dea1817938c55094df7e9cf0220029890a7ab3d8a37c48a449eb9aeee456ce495c678727360a0fb29ca26d3b7c4012103eeb49f8127c4e6524b6bb5b2011f63132cba3f8269855932135fd33bd12678f4ffffffff0fa05a1387c3e041bf8f214c852dd3c67215c7d485e0557a6b0b30f8f538e2ad010000006b48304502210082af9ecce6e387003ebaf882e4b4bb5a168f325905dae1ee6d07199126d71726022005a100e90c2f95d95038639a2ab36d76a7bb3a5fbc168d6885b4cef4179edbdf01210386f6a44593fa741de6a472af30e88c7feba4bb40ec7f93c6acab37def6964b3bffffffff6c2b04749af6b2621b3e437fea8e42dc92fdcb9b52566df36730ad8489f75461010000006a47304402203127b1c0dddd74ab53f8525c7fbd8e0aeb756e99d864898a8b99dba3bf3ccfc302203701d9bae7f380a13a3bfd8f727aad9d5d4c1770253eb109036c7f1c6d465e1c0121039be166345c407b47cdf2e4367193dc977fb3177fee9a0c2ddf62b5bf3b34f595ffffffff232b3e1b869ce9460de11a990e2d210c869242f09f48b603b50f122797cb966d010000006b483045022100c344876a4a2c4b2a4bfd9de332c362a542d230e61bde6209325adebfc4b7c85902205d7ae6e0dc97abe09d18e931ee9f8a37e82480bbdc5b565553762f7d5b8dfef90121025e71caad15ad9e820c14c7f8db5fa67d23026c4a54b3f5fbb255176a69506a9cffffffff041fa37d09000000001976a91469f0bd1e4d82d0307f1bbeacb894d332474909ec88ac40420f0000000000db530a752f6d617877656973734cb27b2265787069726564223a2254686973206e616d652077696c6c206e6f206c6f6e67657220626520757064617465642e20416e7920656e747279206166746572207468652065787069726174696f6e206f66207468697320656e747279206973206e6f7420616666696c69617465642077697468206d652e20506c6561736520726566657220746f2069642f6d6178776569737320666f722075702d746f2d6461746520696e666f726d6174696f6e2e227d6d7576a914d53626b2fe2c6d3613f7244cd8f1fe79f4c0141288ac40420f0000000000fd0502530a642f6d617877656973734ddb017b227472616e736c617465223a226d617877656973732e696f222c226e73223a5b223138382e3136362e3136372e3530222c226e73312e626f782e6d617877656973732e696f222c226e73322e626f782e6d617877656973732e696f225d2c22746c73223a7b22746370223a7b22343433223a5b5b312c2237393644464546313237463242343437313446393430444130414443313734353439384541304635304243454335393333453543364536444141444330344330222c305d2c5b312c2244374637334244464438413736343434444537383633334342394534364144393034393544373735343134304241323442423632384643394238373136344446222c305d5d2c223235223a205b5b312c2244374637334244464438413736343434444537383633334342394534364144393034393544373735343134304241323442423632384643394238373136344446222c315d5d7d7d2c226473223a5b5b34373032382c372c322c225a717538537934753366434531536d574b6247772f7a6c7a6b45554263303266545147724d44304864586b3d225d5d2c22656d61696c223a20226d61782b706f73746d6173746572406d617877656973732e696f222c22696e666f223a226d6178406d617877656973732e696f227d6d7576a914353b5ded5ffde1c37a4d2df77d7e182f7823d7c288ac40420f0000000000fd2602530b69642f6d617877656973734dfb017b226e616d65223a224d6178696d696c69616e205765697373222c22656d61696c223a226d6178406d617877656973732e696f222c2274776974746572223a22404d61785765697373506f6b6572222c226b657962617365223a226d61787765697373222c226269746d657373616765223a22424d2d3263536d4a354b4d42594454525568574e67367752364342776e6176666954616361222c22626974636f696e223a22314d61785765374275314d63564d4a35774a44363532645759384a52717a694a5050222c2277656273697465223a226d617877656973732e696f222c22677067223a7b2276223a22706b6131222c22667072223a2230374341334143443936454542344642464630373042324542314635323836363031313535414246222c22757269223a2268747470733a2f2f706173746562696e2e636f6d2f7261772f426e564d78414e4a227d2c22726573756d65223a2268747470733a2f2f676f6f2e676c2f6b4339384c4d222c226e6f7465223a22426c6f636b20323438313539206e6f7420636f72726563742c206e657720696e666f20696e2027696e666f27206b6579222c22696e666f223a2268747470733a2f2f69706e732e6d617877656973732e696f2f516d566252514b5736666348327a65576e4b54434a774442697276395757583670647677525575444777436e3978227d6d7576a914d77dadfae12a9767b2fc7f92dea13211ff54b61088ac00000000

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

@domob1812 Is there any likelihood that this is triggered by a bug
that Bitcoin Core may have fixed upstream (which would be in our dev
branch), or is this almost certainly a bug on our end?
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYOq1IAAoJELPy0WV4bWVwUo0P/iF+QtgC1oB7/LtKw5fOKtKb
expk/FRUBpcsrtAqZBPEC7XFna1YN2kS/v710yxD+80W7aPr8yDkkuDItYtIEJez
GTFgUx1zgmm5FjL7PnvQ17yEjhmN4S722arrDxcfDL8xcP3WKOVfFPeNHLw3FYOW
CQslYgAERaZFjCxC14f84dLaVPQMP/dnKgiufI9nF6lluxDGlL1XZ6KX7wCiUinx
nrkkFWAkfdlJBMYxlyeRhlkX53V9jXXwvt/bI4uQmffxx/Ij4sD0yruR7A7WDuGs
iHL1yMxXroi+OVkxteCV4r70JspckPxyEXsOumWUhIQQb7XdTiC7Y12uqjb75GOX
OWuS+KAE+wWOf5Jp9eR2Z285T2xqzOwAKyh/z1apagvvZwpUS9qonSnSCoC6CT2C
9k6wPo0YaEZd/GxCzzAO6sOlwwwOtos5XK8tgcsFJoRW3q4+eEEr1OZtWlUEd4x2
FsCs5NWNEm3gQwGWNlg0xw/XmWRgtipgEbNiH7iQLfszfHd2LYkwbiQDRNYLt8eC
bYmBvR5TDGbRsKPJGo2Bxefj8ZEU450Di6Xkcf2R8zIkKP0WYLMWVBm2udlVl0od
yE9FNNoGCpRZ6mXesN7uL/IjhlYckFDgE5wHc8EPO+C80LwexEU/hvrZF3QHzcrL
KIezODjnrThZFwubjjHw
=wqrR
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
This looks very much like a bug on our side.  Probably the checks are just too aggressive, triggering an assertion crash for something that can actually be reached by user input.  I generally try to be quite aggressive in asserting, especially for something like Namecoin; a crash in a situation like this is better than a bug that loses money.  I'll take a look when I have time.  Probably it is easy to fix.

**Comment by domob1812** [comment]
Proposed fix is in #117.  Please test and review, if you have time.  If it looks good, I'll merge it to all relevant branches (`dev`, `master` and `0.13`).

**Comment by domob1812** [comment]
Merged #117 to `dev` now.  I don't think it makes much sense to backport this, since it is a rather academic issue and now fixed on the main future development branch.  But feel free to reopen this issue and request a backport to `0.13` or `master` if you think it is worth the time.
