### ISSUE TITLE
Rebrand NSIS images

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#135]
Several of the images used in the NSIS installer have the Bitcoin branding.  The offending images appear at first glance to be these: https://github.com/namecoin/namecoin-core/tree/dev/share/pixmaps

We should rebrand them to have the Namecoin branding.

**Comment by JeremyRand** [comment]
Would @fsb4000 possibly be interested in this task?

**Comment by fsb4000** [comment]
@JeremyRand , sure https://github.com/namecoin/namecoin-core/pull/136

**Comment by domob1812** [comment]
I assume this was fixed in #136.  Feel free to reopen if not and anyone still wants to work on this.
