### ISSUE TITLE
getmemorypool

### ISSUE THREAD

**Issue by banjochose** [namecoin/namecoin-core#139]
Hi I am missing "getmemorypool" command can it be re-added ? I think it was back than in "namecoin-legacy"

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

banjochose:
> Hi I am missing "getmemorypool" command can it be re-added ? I
> think it was back than in "namecoin-legacy"

getmemorypool was removed in upstream Bitcoin Core in v0.7.0; it was
replaced with getblocktemplate, submitblock, and getrawmempool [1].
Do those RPC calls meet your needs?

[1]
https://web.archive.org/web/20161018140139/https://en.bitcoin.it/wiki/Or
iginal_Bitcoin_client/API_calls_list#Full_list

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYYxgjAAoJELPy0WV4bWVwEXMQALShgIpzNmzzknjW6hRnOcwf
1KVCiSPPwC3RM94gi/5kxvLN6YyaEmye3MMHyxP3XLAoj8cJ2bdfEoWc4kCJvmUN
QHE5Fsxl0e8gi5xUpotx+9aO9Qz57XYBor3ud3MnkEj5tvWSbRCqxq2QaQUMXN+Y
1m0VdEt9Ur1HDBsXqG/4dGC5uKxeXsTRth0IbJmK040u3mfxbKRfNqLBDQ69/blx
ELUKsmHHtbEP/Yry8Pad3Wf2C8jwOE/UxkKMvm+fX50izmEZklabhQqcheb67PwT
T/ZNdVDJHOT36K+jk5H9nbsAvORkdCddr6WgUMkEGl9pvi9nvBgxSvcQX6Ge7jXd
2rw4CTNYSjwufh6d5DqcP8GDX0BQS3V/QkGO5BfpIh/jNlr+54IoDzhhsCXTuuls
Quy8dAm/OV1dH+tITyVQDjndvsqmdnx5G5QVPr2qontZTX6nDyesQ8nNAs3Upl/Z
pF77w7h9R55gLYmMG9oxKnxZXPvqDP4rKYu3+iV/i3oqOVhM/KsXqaqcKnT0HDa9
Q0kHXKqBfWYrcuzHAIpyjpD4Bnx0+g08/nCu0+cGFQSm0MUYKlPIrh7tKEcEWMbZ
GJ4fzck9qqF3jh5UgIQy3aNbzY5332UeeQOxJWCQOx5eAUfvEi6Ex6blngb9FXwb
W28acxKd21ImIgmDMW5f
=CBUi
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
As @JeremyRand wrote, you should use the modern Bitcoin equivalents, e. g., `getrawmempool`.
