### ISSUE TITLE
How to migrate old wallets?

### ISSUE THREAD

**Issue by rnhmjoj** [namecoin/namecoin-core#14]
Old wallets from the previous versions on namecoin appear corrupted.
Is there a way to use the wallets or import the data?
See my question [here](http://bitcoin.stackexchange.com/q/38314/27132)

**Comment by phelix** [comment]
As far as I know the wallet format stayed the same. A copy of the file worked for me after a normal start.

**Comment by JeremyRand** [comment]
@rnhmjoj Which OS are you on, and is your previous Namecoin version compiled by you, or from an official package?

**Comment by rnhmjoj** [comment]
It was OSX, compiled by me. I'm also using the very same wallet on another machine that runs the AUR package [namecoin-core](https://aur.archlinux.org/packages/namecoin-core/) 0.3.80.

**Comment by JeremyRand** [comment]
@rnhmjoj Has that wallet ever been used on an unofficial Namecoin release (e.g. self-compiled) which was built with a current version of BDB (or more recent than the version used in official Namecoin releases)?  If so, BDB will silently upgrade the database format, and it will appear to work until you use it with an older version of BDB (such as the official Namecoin releases), at which point you will get a corrupt wallet error.

**Comment by rnhmjoj** [comment]
Yes, that must be it. Sometimes I had to recompile namecoin (I think I've always used the latest tag) because berkley db has been updated by homebrew.

**Comment by JeremyRand** [comment]
@rnhmjoj Ok, yeah, that'll be it.  Sorry you ran into trouble with this -- we probably should document more clearly that newer BDB versions will break things.  (The same thing will happen with Bitcoin, as far as I know.)
