### ISSUE TITLE
Transaction decode is currently broken in namecoin-core/master as of commitid 54bef2b7d78ddb2c68708ddda7e7ca6c2554943e

### ISSUE THREAD

**Issue by midnightmagic** [namecoin/namecoin-core#140]
Take the following transaction, which appears in block 282446:

0071000002c323b5df3dbd501ef8e26683749fd13f785eac6d4f4c2083196a33262605e6ec010000008b48304502207cc397996cf41a4be7ce229226c2e3862557256e372dd325dfefaba26a4a44a20221008e71fc315563d04d7d92d6e2b0ef9c5e095df50777664819623156dcf3ec1c1e0141045bc24b6e33ecbe341e8195b4e8fcb3f8c7937ca6f671f799644968dc00e82d0160c5e14b687cba83840381dda04711939a225588eb0e2401d4f14dc9d3a5ccdaffffffff882be8eb700e1c6eaef2682839293ae9d5bfacf82cee80510d4dee6eed359c98000000004847304402206c6115eb47b4f3010a6c0e79ea5ee7f036fc1da22af172c4bd39a460758bb34402204cc40302837a3a61d9b1e12a99e73572f95da7b5005e5ce842a7b8b4ba90d7f901ffffffff02e007646300000000434104fb090d04c8f110012a9f4545b6cb1f93a6f22db1b35bef7e1545a4a0aef0124cd25c522851ba2120f12b124785adc6f09b13f8eaa294cfe54a601dc75f11df29ac40420f00000000005a5303662f6a394269746d65737361676520616464726573733a20424d2d3263554755687335436a6973526975514756574447334a514a47717a5967713134356d7576a9147368feca713f2a9d7780343b74007e26a4fcfcea88ac00000000

Older versions of namecoin at one point decoded vout:1 from the above as either, if you were doing a full block decode:

"scriptPubKey" : "3 662f6a 4269746d65737361676520616464726573733a20424d2d3263554755687335436a6973526975514756574447334a514a47717a596771313435 OP_2DROP OP_DROP OP_DUP OP_HASH160 7368feca713f2a9d7780343b74007e26a4fcfcea OP_EQUALVERIFY OP_CHECKSIG"

One of the online block explorers shows it as:

OP_NAME_UPDATE 3:662f6a 57:4269746d65737361676520616464726573733a20424d2d3263554755687335436a6973526975514756574447334a514a47717a596771313435 OP_2DROP OP_DROP OP_DUP OP_HASH160 20:7368feca713f2a9d7780343b74007e26a4fcfcea OP_EQUALVERIFY OP_CHECKSIG

Any of these other forms can be parsed, but the one currently in decoderawtransaction seems to be incorrect?

I wonder if this is the same bug, accidentally re-imported from Bitcoin in the transition, that I fixed all those years ago. :-)

**Comment by midnightmagic** [comment]
asm is currently decoded in:

src/core_write.cpp:75 in ScriptToAsmStr()

Yeah, looks like a similar bug. For namecoins with proper names of a size less than 4 bytes, the asm decoder is incorrectly presuming it is an integer. See on:

src/core_write.cpp:90

    if (vch.size() <= static_cast<vector<unsigned char>::size_type>(4)) {

So this is incorrect. As per my ancient fix for this, the correct interpretation of this in the event we have OP_NAME_* is to use the hex instead, since it's a string. I can do another pullreq about it.

**Comment by domob1812** [comment]
I get (with 0.13) for the tx you list:

    {
      "txid": "637703fbe4df4e878a4d0136f0a1533d50694a79515086cec4fe0e3b9bd69203",
      "hash": "637703fbe4df4e878a4d0136f0a1533d50694a79515086cec4fe0e3b9bd69203",
      "size": 478,
      "vsize": 478,
      "version": 28928,
      "locktime": 0,
      "vin": [
        {
          "txid": "ece6052626336a1983204c4f6dac5e783fd19f748366e2f81e50bd3ddfb523c3",
          "vout": 1,
          "scriptSig": {
            "asm": "304502207cc397996cf41a4be7ce229226c2e3862557256e372dd325dfefaba26a4a44a20221008e71fc315563d04d7d92d6e2b0ef9c5e095df50777664819623156dcf3ec1c1e[ALL] 045bc24b6e33ecbe341e8195b4e8fcb3f8c7937ca6f671f799644968dc00e82d0160c5e14b687cba83840381dda04711939a225588eb0e2401d4f14dc9d3a5ccda",
            "hex": "48304502207cc397996cf41a4be7ce229226c2e3862557256e372dd325dfefaba26a4a44a20221008e71fc315563d04d7d92d6e2b0ef9c5e095df50777664819623156dcf3ec1c1e0141045bc24b6e33ecbe341e8195b4e8fcb3f8c7937ca6f671f799644968dc00e82d0160c5e14b687cba83840381dda04711939a225588eb0e2401d4f14dc9d3a5ccda"
          },
          "sequence": 4294967295
        }, 
        {
          "txid": "989c35ed6eee4d0d5180ee2cf8acbfd5e93a29392868f2ae6e1c0e70ebe82b88",
          "vout": 0,
          "scriptSig": {
            "asm": "304402206c6115eb47b4f3010a6c0e79ea5ee7f036fc1da22af172c4bd39a460758bb34402204cc40302837a3a61d9b1e12a99e73572f95da7b5005e5ce842a7b8b4ba90d7f9[ALL]",
            "hex": "47304402206c6115eb47b4f3010a6c0e79ea5ee7f036fc1da22af172c4bd39a460758bb34402204cc40302837a3a61d9b1e12a99e73572f95da7b5005e5ce842a7b8b4ba90d7f901"
          },
          "sequence": 4294967295
        }
      ],
      "vout": [
        {
          "value": 16.67500000,
          "n": 0,
          "scriptPubKey": {
            "asm": "04fb090d04c8f110012a9f4545b6cb1f93a6f22db1b35bef7e1545a4a0aef0124cd25c522851ba2120f12b124785adc6f09b13f8eaa294cfe54a601dc75f11df29 OP_CHECKSIG",
            "hex": "4104fb090d04c8f110012a9f4545b6cb1f93a6f22db1b35bef7e1545a4a0aef0124cd25c522851ba2120f12b124785adc6f09b13f8eaa294cfe54a601dc75f11df29ac",
            "reqSigs": 1,
            "type": "pubkey",
            "addresses": [
              "NFJvz6BCArJGuQYpdCkusrtuaZzZJxt6kh"
            ]
          }
        }, 
        {
          "value": 0.01000000,
          "n": 1,
          "scriptPubKey": {
            "nameOp": {
              "op": "name_update",
              "name": "f/j",
              "value": "Bitmessage address: BM-2cUGUhs5CjisRiuQGVWDG3JQJGqzYgq145"
            },
            "asm": "OP_NAME_UPDATE 6958950 4269746d65737361676520616464726573733a20424d2d3263554755687335436a6973526975514756574447334a514a47717a596771313435 OP_2DROP OP_DROP OP_DUP OP_HASH160 7368feca713f2a9d7780343b74007e26a4fcfcea OP_EQUALVERIFY OP_CHECKSIG",
            "hex": "5303662f6a394269746d65737361676520616464726573733a20424d2d3263554755687335436a6973526975514756574447334a514a47717a5967713134356d7576a9147368feca713f2a9d7780343b74007e26a4fcfcea88ac",
            "reqSigs": 1,
            "type": "pubkeyhash",
            "addresses": [
              "N76bgubJyg6FRE4jgrNSfDQRJiYfcCZFts"
            ]
          }
        }
      ]
    }

I've explicitly added logic to add the `nameOp` field present in the decode, and there is even a regression test for this IMHO.  I've not touched the `asm` decoding, though - so feel free to submit a pull request if you prefer to change it in some way - ideally including a regtest in `name_rawtx.py`.

**Comment by midnightmagic** [comment]
Okie doke. Will do then.

**Comment by domob1812** [comment]
Proposed fix is in https://github.com/namecoin/namecoin-core/pull/162, needs rebasing but otherwise should be good.
