### ISSUE TITLE
Is it compatible with nomp pools?

### ISSUE THREAD

**Issue by AndreyNag** [namecoin/namecoin-core#144]
Is it compatible with nomp pools? Or i need use other fork?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

AndreyNag:
> Is it compatible with nomp polls? Or i need use other fork?

Should I know what exactly nomp polls are?  A quick Startpage brings
up https://github.com/zone117x/node-open-mining-portal , are you
asking about that software?


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYzhOMAAoJELPy0WV4bWVw2WoQAJwlj+D0L7C0crtomfbeCHtz
ll+RQ9QHh5hQ37VsLSnY/uSOIFajBIQs1NR6GBjjzbA3s948a6Q79WrwJf2/7NNy
Oolti/sQ9masYZCOZVFi3OqgIMQFMgfGBLCGEdKUYKn8j0SyAqjqfYPA7u/nX3NN
jH5LlZAVimIyEjnM8TCEgunL3LRb6DFbgDbfGxcs2ghyad1YUf3bvsc47bd0F5so
ChuM6wmKpkMDP5c7XvsFfINRdFH3jzr27QBZXdxUdU2Txsyk7IjzVwssKbb3GBGV
kazAZW5RSV5DsBisTaFB1g0gUO8V1Ke2kUkH27EUk6FEWAhr/QwCX6cpsZRtwNW5
Y0wg66fidBLHH8b9L5Xh02yovey6ABn737PZfUp+9awAq2sTvRNPvpFb2IekpCkJ
3dhjKErad2QwDGXcuTgCG6Ll7IbC4Glt4C1OM0/HhAuHJFNmvSDQ5KbyTjL/Nn9h
vosnfbzLyWpcfr/u9ebWBj4ZNJdZTnWhdyp1jlCaX0g1AsYvN8vm+j9Mho7lLxen
ciGHNq402KA1CerCZ8rE3Fw4VMRsjsz/5JTwxP0WAICW9EEN0a/H8l40m+216/Pu
2uzXAPOE+gN9v9gvukGU1R9nVAOuy/8hmdfTAXVloGujXtkgj4kOsD8Uk18yxABB
IjssL/JFjReCWHSO23/n
=o2Ee
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
Closing as obsolete.  Feel free to reopen if the question is still relevant and you have more information (as per @JeremyRand's comment).
