### ISSUE TITLE
Utils: namecoin-tx should support creating name outputs

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#147]
`namecoin-tx` currently supports the following output commands:

* outaddr
* outpubkey
* outdata
* outscript
* outmultisig

But it doesn't support name outputs.  I suggest adding additional output commands for creating name outputs.  It should support name_new, name_firstupdate, and name_update, in combination with any of addr, pubkey, data, script, and multisig.  It should also permit binary data to be used for any of the name opcode arguments.

**Comment by JeremyRand** [comment]
The `namerawtransaction` RPC proposal in https://github.com/namecoin/namecoin-core/issues/181#issue-255132152 might be a good way to handle the requests in this issue (besides the binary data support, which is blocked by https://github.com/namecoin/namecoin-core/issues/164 )

**Comment by JeremyRand** [comment]
This issue is blocking some scalability analysis that I'd like to do (both for public documentation purposes and for responding to an inquiry from ICANN community people).

**Comment by domob1812** [comment]
Let's take this up.  I agree that the way to support name operations in `namecoin-tx` should be similar to how `namerawtransaction` works.  In other words, you first create an output using any of the existing features of `namecoin-tx` (supporting all the different types of scripts), and then you just "add" a name operation to it in a later step.

Here's a proposal for how the new commands for adding name operations could look like:

- `namenew=N:NAME:RAND`:  Add a `name_new` prefix to the existing output with index `N`.  `NAME` and `RAND` are hex encoded (similar to how `PUBKEY` and `SCRIPT` work with the existing commands).
- `namefirstupdate=N:NAME:VALUE:RAND`:  Add a `name_firstupdate` prefix with the given hex-encoded parameters to output `N`.
- `nameupdate=N:NAME:VALUE`:  Add a `name_update` prefix to output `N`.

This is straight-forward, fits in with the existing commands of `namecoin-tx`, and supports full binary names/values out of the box.  @JeremyRand and others, what do you think?

**Comment by domob1812** [comment]
@JeremyRand:  This is now implemented (I just merged #240).  So in case you were still blocked on your analysis and didn't work around it somehow, you are now free to go. :)

**Comment by JeremyRand** [comment]
Excellent, thanks @domob1812 !  This is good timing too, seeing as someone I met earlier this month at DWS is very interested in the scalability analysis I was doing.
