### ISSUE TITLE
Support specifying rpcpassword by file

### ISSUE THREAD

**Issue by basvandijk** [namecoin/namecoin-core#148]
Currently the `rpcpassword` must be specified in the `namecoin.conf` configuration file. On some systems (for example [in NixOS](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/namecoind.nix#L14)) configuration files are stored in world-readable locations. It's a bad idea to store secrets in world-readable locations.

To better support these systems it would be nice if there was a `rpcpasswordFile` configuration parameter. Users can then keep `namecoin.conf` in a world-readable location but set  `rpcpasswordFile` to a file with restricted ownership and permissions.

**Comment by basvandijk** [comment]
Good tip! I created: https://github.com/bitcoin/bitcoin/issues/10071.

**Comment by domob1812** [comment]
Closing this, since it is indeed an upstream issue (and was already brought up with Bitcoin).  Also, as mentioned in the Bitcoin issue, there are now alternatives to password authentication (e. g., cookie files).
