### ISSUE TITLE
Assertion `pindexPrev' failed.

### ISSUE THREAD

**Issue by Dobredan** [namecoin/namecoin-core#15]
Hello, my Namecoin got a problem

./namecoind
Namecoin server starting
namecoin@server ~/namecore/src $ namecoind: main.cpp:3004: bool AcceptBlockHeader(const CBlockHeader&, CValidationState&, CBlockIndex**): Assertion `pindexPrev' failed.

I already tried 
namecoin@server ~/namecore/src $ ./namecoind -reindex
but I got the same result.

Any advice?

**Comment by domob1812** [comment]
This is strange.  As far as I can tell, the code in question is the same that Bitcoin uses.  You can try running the latest version of the Github sources, in case you don't.  Possibly this is a bug that was already fixed.  Apart from that, it could be some kind of damage to your blockchain directory - if you do not mind the trouble, you can try redownloading the blockchain.

If the problem presists even after a fresh download, can you please post the last lines of debug.log?  Also, if you can, it would be great to get a recipe for reproducing the crash so I can look at it with a debugger.

**Comment by JeremyRand** [comment]
Hi @Dobredan, were you able to get this fixed?

**Comment by domob1812** [comment]
Closing this as likely obsolete.  Feel free to reopen if the issue still persists.
