### ISSUE TITLE
Dont understand which wallet?

### ISSUE THREAD

**Issue by imrecsoka** [namecoin/namecoin-core#158]
Hello, i do not understand which wallet to download for namecoin?
I have downloaded Namecoin Core version nc0.13.99-name-tab-beta1 (64-bit)  (windows 7 64 bit OS)
Unsure if this is correct ?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

imrecsoka:
> Hello, i do not understand which wallet to download for namecoin? I
> have downloaded Namecoin Core version nc0.13.99-name-tab-beta1
> (64-bit) Unsure if this is correct ?

https://www.namecoin.org/download/ lists the recommended downloads.
As per that page, 0.13.99-name-tab-beta1 is recommended for general use.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZCnVFAAoJELPy0WV4bWVwZ0MP/RBZcVtxM23Wsr8qDnmfdI5u
ocZWxXHAvtGpvNoX26vvFVtZWvXpxNSqoof1gFNx+J8OA3wMlDHFrjDbuJrtprAz
jnXHm56ND+vQHLwkC/VpewfkJdtoUtY0HT9c72zn4Gy7JlmVwvCeteLzYDPrsrG6
Y7xoAsEskhfEezME8yFOjIqA7szXu2NYE8J3hYlEtcutaL+0WbvkX3Ih1mjMZK2z
aurEgUsbjIrWPRlR9VHNoE9rfQhcdFmd0VhuOtmu1dtr3pwhXqLvgoW9lSDhbxTM
sZJZ6CAZF0H/zkmHdMH1Vl6tcLShYa9i9JfElcFL6h7I2uyF4hQ9u4tFL2ZuAGqR
8997PlTZic9+VlDD6d55yuvceKNzlcI2hLhEKwUUjUpjZhlVKcLFmL8emYKkEh2a
ufNr+pt+4FnNs1wTa6plgzdiL1WHtUuahOYCmcyXtSMwVAY8k10IOgtkT+CxRE9z
/ga+LVVnkb3ZFYsvAthvZ4PB+85otw/EK0kZt9bJtR2FvTMm0//8bz2br/h2XhPk
jQONLZm/Jmh2bLAmTgofbKJxGzzCg3n0eUN5WvBZSArJipUyltAdyfvSO3JDxdee
CdKTK29POUh4giPPgOSHrpvnZv1Yg0VBApwchCoM/R2BVV49TQfV02I9mzaaEGPU
U+wyOtwzdWRBLsdR4EbC
=EHKy
-----END PGP SIGNATURE-----

**Comment by imrecsoka** [comment]
Okay so it seems i have the right wallet. 
Unsure what is next , i will have to see, thanks.

**Comment by JeremyRand** [comment]
Appears resolved, closing.
