### ISSUE TITLE
Build: macOS "make deploy" needs to be rebranded

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#167]
### Describe the issue

The macOS `make deploy` build script needs to be rebranded from Bitcoin to Namecoin.

- [x] Rebrand name.
- [x] Rebrand logo.

### Can you reliably reproduce the issue?

Yes.

#### If so, please list the steps to reproduce below:

1. Build Namecoin Core for macOS (without Gitian).
2. Make sure that you run `make deploy`.

### Expected behaviour

It should produce `Namecoin-Qt.dmg` with the Namecoin logo.

### Actual behaviour

It produces `Bitcoin-Qt.dmg` with the Bitcoin logo.

### What version of namecoin-core are you using?

Honestly not certain of the commit hash since I don't have access to the macOS machine right now.  It was the latest commit of the `dev` branch as of 2017 April 28.

### Machine specs:

- OS: macOS

Not sure of the rest of the specs, as I don't have access to the macOS machine right now.

### Any extra information that might be useful in the debugging process.

I suspect that these 2 files are the culprit for the name:

* https://github.com/namecoin/namecoin-core/blob/master/contrib/macdeploy/macdeployqtplus
* https://github.com/namecoin/namecoin-core/blob/master/Makefile.am

I suspect that this file is the culprit for the icon:

* https://github.com/namecoin/namecoin-core/blob/master/src/qt/res/icons/bitcoin.icns

**Comment by jloughry** [comment]
I can reproduce on my machine: Namecoin Core version v0.14.99.0-d9e7358d2 (64-bit) built from source on macOS Sierra 10.12.5.

**Comment by domob1812** [comment]
@JeremyRand: Is this still relevant or fixed now (e. g., with #208)?

**Comment by JeremyRand** [comment]
Yes, this is fixed AFAIK.
