### ISSUE TITLE
"No block source available"

### ISSUE THREAD

**Issue by imkane** [namecoin/namecoin-core#174]
3 years and 20 weeks behind.

Stuck on this ...

Windows 10 64-bit client, latest release.

Other digital currency clients work fine on my computer.

**Comment by imkane** [comment]
I followed these instructions and that helped!

https://forum.namecoin.org/viewtopic.php?f=2&t=2632&view=previous

**Comment by markasoftware** [comment]
This is because the list of DNS seeds and hardcoded peers are outdated. There are several pull requests open to resolve this which will probably be included soon.

**Comment by sidechainintelligence** [comment]
I went to C:\Program Files\Namecoin and clicked the blue "namecoin - qt" Application file  size 31030 KB,  the wallet opened up and began "synchronizing with network..."   This seemed to work for now.

**Comment by domob1812** [comment]
Closing, as this seems to be resolved now.  Feel free to reopen in case it is not.
