### ISSUE TITLE
RPC: createrawtransaction doesn't give sufficient control over name outputs.

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#181]
### Describe the issue

In `createrawtransaction`, the following issues exist:

1. `name_new` outputs are not possible.
2. `name_firstupdate` outputs are not possible.
3. Name outputs with amount > 0.01 NMC are not possible.
4. Multiple name outputs are not possible.  (This transaction type is not currently allowed by Namecoin consensus rules, but `createrawtransaction` shouldn't be doing validity checks, and we should keep the raw transaction API forward-compatible with an eventual protocol upgrade that legalizes this transaction type.)

### Can you reliably reproduce the issue?

Yes.

#### If so, please list the steps to reproduce below:
1. `./namecoin-cli help createrawtransaction`
2. Read the documentation shown.

### Expected behaviour

The use cases described above should be addressed.

### Actual behaviour

The use cases described above are not addressed.

### What version of namecoin-core are you using?

Namecoin Core version v0.15.99.0-ead838c (64-bit).  Self-compiled.

### Machine specs:
- OS: Fedora 25 inside Qubes 3.2
- CPU: Haswell Core i7.
- RAM: Qubes allocates between 400 and 4000 MB to that VM.
- Disk size: Qubes allocates 10 GB to that VM's private storage.
- Disk Type (HD/SDD): HD.

### Any extra information that might be useful in the debugging process.

My first idea was to remove the `name_operation` argument of `createrawtransaction` and instead allow address outputs to optionally have a value that is a JSON object instead of a number/string.  The JSON object would have an `amount` key that holds a number/string representing the amount of the name output, and a `name_operation` key that is a JSON object with all the keys that `name_operation` currently has (except for `address`, and also supporting `name_new` and `name_firstupdate`).

However, I suspect that this would be too invasive to upstream code.  So I suggest instead removing the `name_operation` argument of `createrawtransaction` and add a new RPC command `namerawtransaction`, which accepts as input an existing raw transaction, a `vout` integer, and a `name_operation` object (which has all the keys that `name_operation` currently has (except for `address`, and also supporting `name_new` and `name_firstupdate`).  This RPC command would prepend the name operation to the scriptPubkey of the specified output, leaving the address and amount unmodified.

**Comment by domob1812** [comment]
I like the proposal with `namerawtransaction`.  The only problem I see is that this will make it more complex to create raw transactions (two RPCs needed rather than one now) - but since the raw-transactions interface is designed mainly for scripts, that shouldn't be an issue.

So ACK for this proposal - I may have time soon to work on the change.

Do you think it is fine to just change the API like this, or should we try to be somewhat backwards compatible in some way?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Daniel Kraft:
> I like the proposal with `namerawtransaction`.  The only problem I
> see is that this will make it more complex to create raw
> transactions (two RPCs needed rather than one now) - but since the
> raw-transactions interface is designed mainly for scripts, that
> shouldn't be an issue.

Agreed.  (And the extra RPC call is only needed for scripts that are
handling name transactions; scripts that are doing currency
transactions won't have to do anything special.)

> So ACK for this proposal - I may have time soon to work on the
> change.
> 
> Do you think it is fine to just change the API like this, or should
> we try to be somewhat backwards compatible in some way?

Since `locktime` and `replaceable` don't accept JSON objects, any
attempt to supply a `name_operation` to `createrawtransaction` would
result in an RPC error rather than an unexpected incorrect operation
being done.  So I think it's fine to change the API.

Also worth noting that there's very little usage of the raw
transaction API in Namecoin right now, and most of the existing usage
is either stuff ported from Bitcoin (in which case this change allows
those users to stop special-casing Namecoin, which is good), or stuff
like atomic name trading which only uses the RPC interface because we
haven't yet added it to the Namecoin-Qt GUI (and this change makes it
easier to add useful stuff to Namecoin-Qt, which will eventually
remove the need for atomic name trading users to use the RPC interface).

There's also the fact that when I last tried to use ANTPY with
Namecoin Core, it already didn't work because I guess ANTPY is abusing
some RPC protocol bugs in Namecoin 0.3.80 that don't exist in Namecoin
Core, so atomic name trading users are already going to need to make
some changes to their code, and asking them to do this as well isn't a
big difference.

So yeah, my vote is to just do the change without worrying about
backwards-compatibility.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZr0TvAAoJELPy0WV4bWVwaU4QAMJbF0tzKbBQr/x/kqVyJfAC
DAs+c89MC8Cwr9NZTUQFIkgIelot6HX4EnaFjMD2T37wJm7GNkzAtLhDC/ycgK4M
yGPzpdt5GAXKaZoJyMaAZC8HPrqH16Gr9U8jlhgb1kMkWNuV/k4CYUzVkxGN3Rji
5JNq5zT7u+P3BPZaTiuisIlh7QEuafqn3wh/XdGi8soN4vTjnKnV83BZW3ad1N/v
5wGwh4GD5NObzSyLdstxX5CHPQHlMIzwAWkV8RXRxr5kuD+FF6CuB/VvfyXoQMOS
xXqoZAZiYZ3YZyPoJdKvStvVDO9L1tOzCjzTME1D7D6TZxNoT43VaytZKCZrjN00
8PIQwlQFUvfA88RzjN3PLlzeTolHW2pE8ieu+0zbwo7//oIlh7/+2NbaWA0tu5RN
6dbhm6P0/WSThlhzM3ll83f0KwXOlHcg5Mn/uXim0VRo8U7ZnDBJIxEuSHUnC1kd
/BI1iEysSCkV79YaE/8hF2q9iHdD6d1wn0KTOOZilSAt+eHgGDpefkmhOEjkU1XP
IuB+lQ17LUfHPP0trdwO5uOf3D7l82gRyKDZSbqaBNzEQNX6DtnxEl1wMbK1NN7v
xnlWvQvIYXQL3AhBYvzq9ddzbP2e+RsSXfdM1T6btX1mIBG9aA0mwIa7xLfKg+TO
jJCoy48CW5W0PXNuEP/m
=UzjR
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
Regarding https://github.com/domob1812/namecore/commit/0026decbdb52c489464f8c32c8373d53248dbb0f , is it feasible to make the nonce optional for `name_new`, so that if an explicit nonce isn't provided, Namecoin Core generates a random nonce (same behavior and implementation as the `name_new` RPC call)?

**Comment by domob1812** [comment]
@JeremyRand Yes, the nonce could be generated if missing - but then we would also need a way to tell the nonce to the caller, since it is required for the `name_update`.  This would mean that we cannot simply return the modified tx hex string from the method.  I don't think it is worth it to make the return a JSON object just for this one situation.

**Comment by JeremyRand** [comment]
@domob1812 Presumably the nonce could be extracted by the caller from the raw transaction that's returned, right?  That seems cleaner than returning a JSON object (which I agree would be unwieldy).

**Comment by JeremyRand** [comment]
Oh, right, the nonce isn't actually parseable that way.  Disregard previous comment....  Hmm, so there are 2 ways we could deal with that: either return a JSON object, or have an extra RPC command for generating the nonce.  Not really sure which works better.

**Comment by JeremyRand** [comment]
FWIW I suspect that making the end user supply a nonce is likely to result in footgun scenarios, e.g. people using low-quality PRNG's.  Generally my goal with these changes is to allow the user to customize an arbitrary part of the transaction creation process, without forcing them to customize the parts they don't want to customize.  The use cases I have in mind definitely don't require customizing the nonce generation (and honestly I'm having trouble thinking of a use case for customizing the nonce generation).

**Comment by JeremyRand** [comment]
@domob1812 `fundrawtransaction` and `signrawtransaction` both currently return a JSON object, so I think there's sufficient precedent for returning a JSON object in this scenario.

**Comment by domob1812** [comment]
I'm typically leaning towards the minimalistic approach, but I agree that generating the random numbers for users is probably not a bad idea.  I still feel that it is "a bit" overkill to return a JSON object just for this one particular case (for `signrawtransaction` and `fundrawtransaction`, at least more data is returned and that data is always useful, not for only one of several cases), but it is probably the best approach and not too bad.

I'll update my PR with this change (which is simple enough).

**Comment by JeremyRand** [comment]
This was fixed by #185, closing.
