### ISSUE TITLE
Configure ERROR

### ISSUE THREAD

**Issue by Abdula-2015** [namecoin/namecoin-core#186]
```
./configure 
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
................................. <skip> ......................................
checking for Linux getrandom syscall... yes
checking for getentropy... no
checking for getentropy via random.h... no
checking for sysctl KERN_ARND... no
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing, Namecoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)
```

### Machine specs:
- OS: Debian 9 / 64bit
- CPU: i3
- RAM: 8 GB
- Disk size: 2TB
- Disk Type (HD/SDD): HDD

**Comment by Abdula-2015** [comment]
Nobody answers ..... Namecoin-Core is no longer supported? :-(

**Comment by domob1812** [comment]
Sure, Namecoin is supported - but we are all volunteers, and in my case, I mostly have time on weekends.  As the error message suggests, you are missing libdb++ on your system - installing `libdb++-dev` through your package manager should fix it.

**Comment by Abdula-2015** [comment]
Thanks! I'll try to do it now.

**Comment by Abdula-2015** [comment]
Ops: And again the configuration error!!!
`configure: error: Found Berkeley DB other than 4.8, required for portable wallets (--with-incompatible-bdb to ignore or --disable-wallet to disable wallet functionality)
`

**Comment by domob1812** [comment]
As the error says, you need to either install BDB version 4.8, or use `--with-incompatible-bdb`.  It is not entirely clear to me from your last post, but it seems you did that, and then you get the last error about "boost sleep"?  I don't know exactly what you need to do for that, but presumably install some more Boost packages.  Perhaps `libboost-chrono-dev` or `libboost-timer-dev`.

Note that all this is nothing specific to Namecoin, but inherited from Bitcoin.  So you should be able to find instructions in tutorials on how to install Bitcoin Core, and if you feel like there's room for improvement, raise an issue with Bitcoin Core.

**Comment by domob1812** [comment]
BTW, I'm closing this again as this seems to be more about technical support than an actual bug (if you think it is a bug, please state more clearly what you expect to be changed -- and then, ideally do so with upstream Bitcoin Core).  For technical support, you will find more timely responses in our forum at https://forum.namecoin.org/ or maybe the IRC channel.

**Comment by Abdula-2015** [comment]
It was with great difficulty that I collected this disgusting clumsy assembly.  The version 0.15.99.0-gda78eaee6 was received.  It has very low quality and a lot of problems when assembling and starting.
But the most important thing is that there is no "Manage Names" tab!!!
but in the old version of nc0.13.99-name-tab-beta1 this bookmark - is there!

Therefore this program is useless! Because I can not manage domain names!
Who made this application so neutered and why???

And when he will turn from pre-release to the final?

**Comment by mkg20001** [comment]
See #187 for the nametab pr. I can imagine there will be a new release after that pr is completed.

**Comment by Abdula-2015** [comment]
But why such a mess in the development of version? 
In the old version of nc0.13.99-name-tab-beta1 there is a tab "Manage Names", but in the new 0.15.99.0-gda78eaee6 it again disappeared?
I do not understand what's going on :(

**Comment by brandonrobertz** [comment]
Namecoin Core got rebased completely againsts upstream Bitcoin Core for the new version. My manage names code is still available in namecoin/namecoin-core at tag `nc0.13.99-name-tab-beta1`. However, I wouldn't recommend using that code as it's deprecated and has bugs.

If you're interested in tracking correct development of the manage names tab, you can find it in my master branch until it's merged into Namecoin Core: https://github.com/brandonrobertz/namecoin-core

Note that all this stuff is experimental, most likely has bugs still, and will be changing rapidly.

**Comment by Abdula-2015** [comment]
<a href="https://savepice.ru" target="_blank"><img src="https://cdn1.savepice.ru/uploads/2017/11/15/cf324d34508f71a5784865d406b8cde8-full.png" alt="cf324d34508f71a5784865d406b8cde8-full.png" title="фотохостинг" border="0"/></a>

**Comment by JeremyRand** [comment]
@Abdula-2015 FYI if you continue to treat developers (who are not paid to reply to you, and who mostly are not paid to develop Namecoin Core either) with hostility, I might decide to invest some time in learning how the GitHub feature for banning a user from our issue tracker works.  Cheers.
