### ISSUE TITLE
"listunspent" should clearly mark (or not show) name outputs

### ISSUE THREAD

**Issue by domob1812** [namecoin/namecoin-core#192]
The `listunspent` RPC command currently mixes currency outputs and name outputs in the current wallet, which is not good (even though the name outputs are marked as `spendable: false`).  Worse, even expired names (whose output no longer even exists in the UTXO set) are present in the output.

What we should fix:
- Expired names should in no case be present in the output.
- For unexpired names, we should either also not include them at all (as they can be queried with `name_list`), or at least clearly mark them with a new field in the JSON result.  E. g., `name: "some_name"` for name outputs, and `name: null` / missing for currency outputs.

**Comment by domob1812** [comment]
@JeremyRand what do you think is the better behaviour - include unexpired names with a clear distinction, or not include them at all?

**Comment by JeremyRand** [comment]
@domob1812 This seems to be a fairly similar issue to expired names being accessible via `name_show` (there is buggy user code in the wild that accepts expired name data from `name_show`).  My opinion is that the best way to handle this (with "best" defined as "least likely to induce subtle bugs in users' code that will remain undetected for a while") is to remove such outputs by default, and have a boolean argument (default false) that enables them (with fields in the output to clearly identify them, e.g. both a boolean `is_name` and a field for the name itself).

This ties into another issue that I've been meaning to file for a little while... I'll write that up for some context.

**Comment by domob1812** [comment]
I assume the "other issue" you were thinking about is #194.

**Comment by domob1812** [comment]
Fixed with #226.
