### ISSUE TITLE
RPC: name_list "transferred" field is undocumented

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#193]
### Describe the issue

The `transferred` field in `name_list` is undocumented.

### Can you reliably reproduce the issue?

Yes.

#### If so, please list the steps to reproduce below:

1. `name_list`
2. `help name_list`

### Expected behaviour

All fields present in the output of `name_list` should be present in the output of `help name_list`.

### Actual behaviour

`transferred` is present in the output of `name_list` but not in the output of `help name_list`.

### What version of namecoin-core are you using?

cc1d2af330ca2275868cca0e960f1c531d736ed2 merged into 3cdcfe7df8b7565171b4a53b13729c261378227d, self-compiled.

### Machine specs:
- OS: Fedora 25 inside Qubes 3.2.
- CPU: Haswell i7.
- RAM: Max 4 GB assigned to Fedora; host has 16 GiB.
- Disk size: 15 GB private storage assigned to Fedora.
- Disk Type (HD/SDD): HD.

**Comment by domob1812** [comment]
See also #219.  I think we should still fix this (which requires slight changes to the `getNameInfoHelp` function signature), but later have to update the help text accordingly in #219.
