### ISSUE TITLE
Use an alert key that we control

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#21]
As far as I can tell (maybe I'm wrong), Namecoin Core is using Vince's alert key, which we don't have control of.  If that is correct, we should create a new alert key.

**Comment by domob1812** [comment]
Yes, I just copied the keys from the old client.  It is on my todo list to change them at some point in the future.  If you want to suggest a way to move forward, feel free to go ahead.

**Comment by JeremyRand** [comment]
I'd really like this to be fixed before we try to deploy the BIP 9 hardfork.  Hardforks are already hazardous enough; trying to do one without an alert key gives us no ability to take action in case of an emergency.

**Comment by domob1812** [comment]
I have no objections, although I'm not sure it is really that important and useful for the fork.  We have usually been quite able to communicate important things in the past, no?  Nevertheless, we should do that, obviously.

Do you know how to generate a key and how to send alerts with it?  I have no idea so far, that's part of the reason why I didn't bother to change things.

**Comment by JeremyRand** [comment]
> Do you know how to generate a key and how to send alerts with it? I have no idea so far, that's part of the reason why I didn't bother to change things.

So I asked on #namecoin-dev IRC, and turns out that this info is not well-documented, nor well-known even by Bitcoin developers.  I'm still in the process of gathering info on this topic, and I'll post here a summary of what was discussed on IRC once the discussion concludes.

**Comment by domob1812** [comment]
Upstream Bitcoin just removed the P2P alert system entirely.  This matches my previous comment that I think we should rely on other channels for communication instead.  This probably makes the issue here obsolete (but I'll leave it open for now in case @JeremyRand or someone else disagrees).

**Comment by JeremyRand** [comment]
I'm okay with closing this, but I'd like to wait a week before closing this, so that other developers have a chance to voice any disagreement they may have.

**Comment by JeremyRand** [comment]
Since no one else has objected and it's been 8 days, I'm marking this as wontfix and closing it.
