### ISSUE TITLE
Namecoin/Bitcoin malloc() error in OpenBSD 6.2amd64

### ISSUE THREAD

**Issue by amore-amore** [namecoin/namecoin-core#210]
I have malloc() error(s) in namecoin 0.13.2 built for OpenBSD 6.2amd64 GENERIC.MP. On previous OpenBSD 6.1amd64 GENERIC.MP
namecoin 0.13.2 works smoothly.

The errors usually occurs every time when Namecoin or Bitcoin started.
The same issue with bitcoin-0.13.2 on the same platform.

OpenBSD developers points on some hidden bugs in memory management used in Namecoin / Bitcoin which float after more strict malloc() was implemented.

------------------------------------------
Here is the error using defalt malloc() settings (no any options were enabled from man(5) malloc.conf): 

namecoind (4563) malloc():bogus pointer (double free?) 0xdfdfdfdfdfdfdfdf
namecoind (4563) free(): chunk is already free 0x1bc9981cae20
OR
namecoind (5850) in free(): double free 0xb4b86701cc0
OR
namecoind (3421) in free(): chink is already free 0x11577e86bb50
OR
namecoind (99023) in free(): chink is already free 0x14e5fe642910

------------------------------------------
After enabling 'S' option "Enable all options suitable for security auditing" by the command:

ln -s 'S' /etc/malloc.conf

The error is a bit different, but persistent.
 
namecoind (2501) in free(): chunk canary corrupted 0x1ad4b3e5b3b0
0x2@0x2 (double free?)

------------------------------------------

I tried to run the namecoin-0.13.2 with 'j' option "Less junking" the malloc() errors still present.
ln -s 'j' /etc/malloc.conf

I can add some further test conditions and build options for namecoin on this platform.

Thanks for attention the problem.

**Comment by JeremyRand** [comment]
If you're seeing the same bug in Bitcoin Core, then I recommend checking whether it's fixed in Bitcoin Core master branch (and reporting it to Bitcoin Core if it's not yet fixed).  We'll merge the fix along with everything else that we merge from Bitcoin Core.

**Comment by domob1812** [comment]
Closing this, as it is likely an issue also present in upstream Bitcoin.  Feel free to reopen if that's not the case and it has to be fixed in Namecoin rather than Bitcoin.
