### ISSUE TITLE
Manage Names tab shows formerly owned names

### ISSUE THREAD

**Issue by tfreedman** [namecoin/namecoin-core#212]
Platform: elementaryOS, Namecoin-Core nc0.13.99-name-tab-beta1

I registered a domain name, then transferred it to a friend. It continues to show up in the manage names tab (along with name_list in the debug console), despite me no longer controlling it. Attempting to change the value field returns "Input tx is not mine."

**Comment by JeremyRand** [comment]
In current master, such names show a `Status` of `Transferred out` in the Qt GUI, and the `Configure Name...` and `Renew Names` buttons are disabled for them.  So I think we can consider this fixed.

If anyone wants to be able to hide such names completely, please open a new issue for that.
