### ISSUE TITLE
name_pending should add a "vout" field

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#216]
# Steps to reproduce

1. Send a `name_update` transaction.
2. `name_pending`

# Expected results

Both a `"txid"` and `"vout"` field should be present (like in `name_show`), so that I know which output the name operation exists in.

# Observed results

`"txid"` is present, but `"vout"` isn't, so I don't have an easy way to figure out which output the name operations exists in.  (I would need to iterate through all the outputs in that transaction, and check which of them is a `name_update` for that name, which is a lot of extra work.)

# Namecoin Core version

nc0.15.99-name-tab-beta1, official release.

# Machine specs

Qubes 3.2 / Fedora 26, Haswell Core i7, HDD.

**Comment by domob1812** [comment]
This was implemented in d1b18a6d55f87e793867ad4c0f186a3ad8cf29bd.
