### ISSUE TITLE
Unify ismine in name_pending and transferred in name_list

### ISSUE THREAD

**Issue by domob1812** [namecoin/namecoin-core#219]
When calling `name_pending` with a wallet, then the `ismine` field is added to the output objects to indicate which names are updating to an address owned by the user.  The output of `name_list` has a similar field, `transferred`, which indicates whether or not the name is now *no longer* owned by the user.

The `transferred` field makes some sense considering that `name_list` only shows names from transactions in your wallet, so that a transferred name is the non-default case.  But I believe negating the ownership-flag is confusing - even more so with two different fields indicating the same bit of information in two different RPC methods.

Thus, I propose to unify the two fields.  In particular, change `transferred` in `name_list` to be `ismine`, with the negated value.  Alternatively, we should at least add `ismine` to `name_list` and add a comment to the help text that `transferred` is deprecated and will be removed in the future.

**Comment by domob1812** [comment]
@JeremyRand and others:  What do you think about this proposal?  Do you think we need to keep the `transferred` field intermittently, or can we just make the change?  This will break client software that uses the field, but updating it is trivial.

**Comment by JeremyRand** [comment]
@domob1812 I'm fine with the proposal, and I think we can make the change without maintaining backwards-compatibility.
