### ISSUE TITLE
Extend name_scan, obsolete name_filter

### ISSUE THREAD

**Issue by domob1812** [namecoin/namecoin-core#237]
We currently have two different RPCs for reading the list of all (or a subset of) names: `name_scan` and `name_filter`.  The main difference is that `name_filter` supports filtering by regexp and by age (number of confirmations).

I think we should unify the two methods.  Based on #194, we can add an optional JSON `options` argument to `name_scan` which allows to specify desired filtering in a more flexible way.  Then we can get rid of `name_filter` and resolve #16 at the same time with a new, specialised option to filter by namespace.

Here's the fields I propose for the new `options` argument to `name_scan`:

- `minConf`: Minimum number of confirmations a name must have.  Defaults to one.  Zero (unconfirmed) is not allowed initially to keep things simple, but we may allow it later and obsolete (or complement) `name_pending` through that.
- `maxConf`: Maximum number of confirmations to allow - defaults to no restriction if not set.
- `prefix`: If set, only include names with this prefix (e.g. `d/`).
- `regexp`: If set, only include names matching this regexp.
- `showExpired`: If true, include expired names.  Defaults to false.  This could also be achieved with `maxConf`, but I think having an explicit option is cleaner, more explicit and easier to use.

One thing to note:  Currently `name_filter` also supports a mode that does not return names but prints stats instead.  I'm not sure if that is used at all (I've never used it), and that functionality would go away with this proposal.  @JeremyRand and others:  Do you think we need to keep this?  If so, we could just add another `returnStats` boolean option.

**Comment by domob1812** [comment]
@JeremyRand and all:  What do you think about this proposal?  Does it make sense, or did I miss some usage for `name_filter` that would not be supported by my proposed extension of `name_scan`?

**Comment by JeremyRand** [comment]
@domob1812 I'd lean toward replacing `namespace` with `prefix`, and make the user supply `d/` (with the forward-slash) rather than `d` (without the forward-slash).  This makes the API a little bit more consistent with Namecoin's internal representation of names as binary blobs, and is also a bit more consistent with how people tend to write Namecoin namespaces (I usually see people refer to the `d/` or `id/` namespace, not the `d` or `id` namespace).

I didn't know there was a stats mode in `name_filter`; I've definitely never used it.  I have no idea whether anyone is using it right now.

**Comment by domob1812** [comment]
Yes, I agree that `prefix` instead of `namespace` is probably simpler and easier to understand.  I've updated the OP accordingly.

No objections to removing `name_filter` when we add equivalent functionality (as per the proposal) to `name_scan`?

**Comment by domob1812** [comment]
It seems there are no more objections to this, so I'll go forward with it.  This will also simplify the remaining parts of #246 after #261, because a) we then already have an `options` argument for `name_scan`, and b) `name_filter` will be gone.
