### ISSUE TITLE
Fix some Namecoin-specific compiler warnings

### ISSUE THREAD

**Issue by domob1812** [namecoin/namecoin-core#245]
@cassiniNMC reported some [compiler warnings](https://github.com/xaya/xaya/issues/52#issuecomment-407200532) he sees for Namecoin.  They probably do not cause real issues but should be fixed nevertheless, as they indicate potential code cleanups.

**Comment by domob1812** [comment]
Fixed the `override` warnings in cd7e3956abe88befbf2eea6de7d69c80128a2e88.

The warnings about holding the mempool lock seem spurious to me, as there is a matching `AssertLockHeld` in all places.   @cassiniNMC, do you see similar warnings being reported for Bitcoin's `txmempool.cpp`?  I think you should - at least I don't see what Bitcoin did differently to suppress the spurious warnings there.

**Comment by cassiniNMC** [comment]
> Fixed the override warnings in cd7e395.

Well done. No warnings related to coins.h or txdb.h anymore.

> The warnings about holding the mempool lock seem spurious to me

You are right, meanwhile they've gone due to some changes in upstream Bitcoin, I assume.

There are a few new ones when compiling https://github.com/namecoin/namecoin-core/commit/58dd556b17ded2f19fbbeec1cc3276e0d41a7d4a , though:

```
net_processing.cpp:1366:13: warning: calling function 'Misbehaving' requires holding mutex 'cs_main' exclusively [-Wthread-safety-analysis]
            Misbehaving(pfrom->GetId(), 20);
            ^
net_processing.cpp:1366:13: warning: calling function 'Misbehaving' requires holding mutex 'cs_main' exclusively [-Wthread-safety-analysis]
2 warnings generated.

```
```
leveldb/util/logging.cc:58:40: warning: comparison of integers of different signs: 'const int' and 'unsigned long long' [-Wsign-compare]
          (v == kMaxUint64/10 && delta > kMaxUint64%10)) {
                                 ~~~~~ ^ ~~~~~~~~~~~~~
1 warning generated.
```
I'm going to check later this evening whether building the relevant Bitcoin version gives me the same warnings.

**Comment by domob1812** [comment]
Thanks - indeed, it seems that we are missing a lock there.  I'll add it.

**Comment by domob1812** [comment]
Pushed a fix for the `net_processing.cpp` warnings to `auxpow` (1d1d71b8f12e099cf2bbcccc3322842346419286).  If you are motivated, you can try to build the `auxpow` branch to see if they are indeed gone for you; otherwise it will be merged to `master` on Monday during the regular merging at the latest.

**Comment by domob1812** [comment]
@cassiniNMC:  Are there any relevant warnings left?

**Comment by cassiniNMC** [comment]
Just tried a build of https://github.com/namecoin/namecoin-core/commit/25ad914f1d3d69bf4e6c3bf99b209bdbb4ed966c :
The logging.cc warning inherited from upstream Bitcoin ist still there.
All the Namecoin-specific warnings, however, have been eliminated.

**Comment by domob1812** [comment]
Ok thanks, then I'll close this for now.
