### ISSUE TITLE
There's no restore feature?

### ISSUE THREAD

**Issue by csharpner** [namecoin/namecoin-core#254]
There doesn't appear to be a restore feature to restore a backed up wallet.

A "restore wallet" menu item under the "File" menu.

There was no menu item under any of the menus to restore a wallet.

Open the wallet.  Open every menu.  There's no restore feature anywhere.

What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?
I'm not using "BitCoin Core".  I'm using Namecoin Core.
nc0.13.99-name-tab-beta1

Windows 10 Pro N, latest updates.
CPU: Intel Core i5-4690K 3.5Ghz (quadcore)
16GB RAM
Boot drive = 512GB SSD
Data Drive = 12TB RAID 3 Tower with four 4TB drives. App is installed on that drive.

**Comment by domob1812** [comment]
As with #256, this is a feature that is missing also for Bitcoin Core - so please open a feature request against them.

You can of course restore a wallet backup - for that, shut down Namecoin completely and manually copy the wallet backup file into your data directory as `wallet.dat` (assuming you are not using the new multiwallet functionality).
