### ISSUE TITLE
No seed words?

### ISSUE THREAD

**Issue by csharpner** [namecoin/namecoin-core#256]
There does not appear to be seed words for me to write down to connect to my assets later.

I expected a feature to show me the seed words to the wallet so I can store them in a safe place for when (not if) my hard drive eventually fails.

No feature found in the UI for accessing the seeds.

Open the GUI and look under every menu item.

nc0.13.99-name-tab-beta1 (64 bit)

Windows 10 Pro N, latest updates.
CPU: Intel Core i5-4690K 3.5Ghz (quadcore)
16GB RAM
Boot drive = 512GB SSD
Data Drive = 12TB RAID 3 Tower with four 4TB drives. App is installed on that drive.

**Comment by domob1812** [comment]
While Namecoin uses a deterministic HD wallet, it does not support showing the seed in the form of words.  This is because also upstream Bitcoin Core does not support that, on which Namecoin is based.  So you should report this as a feature request to Bitcoin Core.
