### ISSUE TITLE
Tests for name scripts and SegWit

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#258]
Now that https://github.com/namecoin/namecoin-core/issues/241 is fixed, we can move onto SegWit.  AFAICT from looking at BIP-141, there are only a couple edge cases that look interesting to me (and I suspect that they're both already handled correctly since it seems hard to screw them up, but best to verify that).

1. Verify that witness validation is enforced (after the softfork activation timestamp) for scriptPubKeys that consist of a name prefix, followed by the standard SegWit syntax of `OP_0 (20-byte P2WPKH witness program)`.  (Basically this is just to make sure that the name prefix doesn't interfere with identifying a scriptPubKey as a SegWit scriptPubKey.)
2. Verify that a name prefix whose beginning looks like a SegWit scriptPubKey (e.g. `OP_3 (32-byte name) ...`) doesn't get detected as a SegWit scriptPubKey.  AFAICT the fact that there are additional `OP_PUSHDATA` / `OP_DROP` / `OP_2DROP` opcodes after the first 2 pushes should prevent them from ever being detected as SegWit scriptPubKeys (and if that's not the case, then I suspect Bitcoin would be broken), but it would be useful to verify this.  Note that witness versions 1 through 3 (which correspond to the 3 name opcodes) are currently defined as "anyone can spend", so it may be a bit tricky to check whether they're being detected as SegWit scriptPubKeys... I assume there's a function for checking whether a scriptPubKey is SegWit (irrespective of what the witness version is), but I don't know if it's publicly exposed to tests.

Refs https://github.com/namecoin/namecoin-core/issues/239 .  Once this is resolved, I *think* the only thing left on my agenda before ACKing everything for the softfork is figuring out the weight limit.

**Comment by domob1812** [comment]
Sounds good - I'll work on this when I find time (although I'm currently busy with a high-priority project for @xaya and will be on vacation later in September).

For 2), I also don't know where such a check is exposed.  But if it is not easy to do this from a regtest, we can do it from a unit test (where the relevant C++ functions should be accessible).

**Comment by domob1812** [comment]
In fact, there actually *is* a bug with names + native segwit programs (not p2sh-segwit, those work fine).  When checking whether a script is a segwit program, the name prefix is not removed.  This has the effect that names at bech32 addresses (native segwit) can be spent by anyone in a block but noone (also not the owner) when going through the mempool.  (But Namecoin in its current form, before activation of segwit, is not affected by this at all.)

I'll work on a fix together with tests for the two things listed above.

**Comment by domob1812** [comment]
69be95dc9b6711ee2eba5b3516ddda42bff1dcab contains a fix for the issue described above, as well as tests covering 1) from the OP.  Before merging this change, though, I would like to add also unit tests for `IsWitnessProgram` to cover 2) as well as in general test the code changes made.

There currently are no tests at all for `CScript::IsWitnessProgram`, also not for the upstream code.  So before proceeding, I would like to get the Bitcoin community's opinion on whether such tests would be useful as well and should be contributed upstream - see https://github.com/bitcoin/bitcoin/issues/14737.

**Comment by domob1812** [comment]
Fix for the issue is in #274, which includes also tests for all the situations described in the OP (at least as far as I can tell - @JeremyRand, feel free to take a look and let me know if you think some test coverage is still missing).
