### ISSUE TITLE
Namecoin error: input tx not found

### ISSUE THREAD

**Issue by creeperslayer69** [namecoin/namecoin-core#259]
"input tx not found"
I have necessary private key and funds to update.

Name would be updated.

https://prnt.sc/kltwl3

Not sure

website

Windows Server 2016/2012

**Comment by domob1812** [comment]
Can you share more details, like the command you used, a tx id or perhaps a hex transaction?  Also, what does your `debug.log` show, if anything?  Without that information, it is not easy to know what exactly you tried and how/why it failed.

**Comment by creeperslayer69** [comment]
I tried to renew a name and that happened. How would I get the debug.log?

**Comment by domob1812** [comment]
The `debug.log` file should be in your data directory.  By default, it is `~/.namecoin` on GNU/Linux systems (but I don't know right now what the path is on Windows).  If you run the Qt UI, you can also open "Help -> Debug window" and there you find a button to open the debug file.

**Comment by domob1812** [comment]
Closing for now.  Feel free to reopen if you have more information to provide / can reproduce the issue.
