### ISSUE TITLE
namehistory / reindex parameter order

### ISSUE THREAD

**Issue by phelixbtc** [namecoin/namecoin-core#27]
```
>namecoind -namehistory -reindex
Error: Error opening block database

>namecoind -reindex -namehistory

```

The second one worked. Is it possible the order of command line arguments matters?

**Comment by domob1812** [comment]
I don't know.  It seems strange to me, but I've not checked the code.  In any case, I suppose that the same happens also with `-txindex` instead of `-namehistory`.  Can you confirm that?  In this case, you may want to open a ticket against upstream Bitcoin as well.

**Comment by domob1812** [comment]
This seems to be working now from a quick test with `-regtest`.  Please reopen if you can still reproduce this.
