### ISSUE TITLE
Add DNS resolving features into Core

### ISSUE THREAD

**Issue by karakozov4** [namecoin/namecoin-core#270]
Namecoin Core in its current form is lacking of DNS resolving features. It's a little odd to not have this feature while the entire project is about being an alternative, decentralized DNS for people. 

Why do users also need to setup and configure other specialized software to resolve .bit domains? This is something like using Bitcoin Core without wallet features and using another software for sending and receiving payments. Users should be able to enable/disable .bit DNS resolving easily from the Core GUI. 

Don't know how hard it is technically, I'm suggesting to integrate DNS resolving features into Core.

**Comment by JeremyRand** [comment]
Merging ncdns into Namecoin Core would make sandboxing/isolation much more difficult, and would force ncdns to be rewritten in a non-memory-safe language.  This is a non-starter.

We're fine with metapackages, which don't have those drawbacks.  You might find ncdns-nsis to your liking in the Windows department, and we'd certainly be pleased if someone wanted to contribute metapackages for other OS's.
