### ISSUE TITLE
Count of how many domains are in the wallet

### ISSUE THREAD

**Issue by danimesq** [namecoin/namecoin-core#272]

**Comment by domob1812** [comment]
What exactly do you mean here?  Do you want this number to be shown / returned from some RPC?  You can get it easily by calling `name_list` and then processing the result with a simple script.

**Comment by DaniellMesquita** [comment]
It is about UI of Namecoin Core, in domain list, show a bubble or something like, intuitively showing to user how many domains he haves

**Comment by domob1812** [comment]
Ok - then it is about the Qt UI.  I have no strong opinion about whether or not we should add that, defering to @brandonrobertz for this.

**Comment by brandonrobertz** [comment]
This would be straightforward to add. We should add this to the GUI spec if everyone agrees it's important.
