### ISSUE TITLE
Add develop branch and contributing.md?

### ISSUE THREAD

**Issue by unsystemizer** [namecoin/namecoin-core#28]
Where should PR's go - master?

Could someone copy `contributing.md` from some similar project and add the guidelines to this repo?
(I see there are Developer Guidelines in `readme.md`, but those are from bitcoin, right?)

**Comment by JeremyRand** [comment]
I think PR's for Namecoin related things go to master, while PR's for generic auxpow things go to auxpow.  @domob1812 would be the expert here.

We're trying to closely follow Bitcoin's repo, so unless they add a contributing.md file, I don't think we will.  There's a pending PR for making readme.md be more Namecoin specific, though: https://github.com/namecoin/namecore/pull/10

**Comment by domob1812** [comment]
Indeed, PRs should go against `master`.  For things that I think should go to `auxpow`, I will ask about a rebase in the PR.
