### ISSUE TITLE
"help getblock" doesn't include "auxpow" field in result

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#289]
# Describe the issue

The help text for the `getblock` RPC method doesn't include the `auxpow` field.

# What behavior did you expect?

The JSON object should have an `auxpow` field.

# What was the actual behavior (provide screenshots if the issue is GUI-related)?

No `auxpow` field is present.

# How reliably can you reproduce the issue, what are the steps to do so?

1. Open a debug console.
2. `help getblock`
3. Look at the JSON object below `Result (for verbosity = 1):`

# What version of Namecoin Core are you using, where did you get it (website, self-compiled, etc)?

`v0.17.99.0-9d496c093`, self-compiled.

# What type of machine are you observing the error on (OS/CPU and disk type)?

VM guest is Debian Stretch with Whonix 14 packages added; ppc64le.

Host is Debian Buster; ppc64le; HDD.

**Comment by domob1812** [comment]
Good catch, seems simple enough to fix - will do that.

**Comment by domob1812** [comment]
Merged #290 to `auxpow`, so this is fixed now.  (Will be merged to `master` soon through the regular upstream merges.)
