### ISSUE TITLE
Downgrading namecoin-core to earlier version overwrites wallet.dat

### ISSUE THREAD

**Issue by Coinomatron** [namecoin/namecoin-core#296]
I had namecoin-core v-0.17.99 running and saw on namecoin.org

"No graphical interface for name wallet. Use the Name Tab Beta (see below) if you require this functionality."

So I did, that version is v-0.13.99. First, it had to rebuild the block database. After that, I had no balance anymore. Turns out it has overwritten my previous wallet.dat

Restoring from a backup doesn't work, as the client on start-up says: 
"Error loading wallet.dat: Wallet requires newer version of Namecoin Core"

For now, I've reverted to 0.17.99

**Comment by domob1812** [comment]
That is most likely an issue that Namecoin inherits from upstream Bitcoin Core.  So I'll close this for now, but feel free to reopen if this issue only appears on Namecoin *and not* on Bitcoin itself.

**Comment by Coinomatron** [comment]
K thanks.
