### ISSUE TITLE
0.11 trying to overwrite '/usr/local/bin/test_bitcoin'

### ISSUE THREAD

**Issue by unsystemizer** [namecoin/namecoin-core#31]
This should probably be changed.

```
Unpacking namecore (0.11-1) ...
dpkg: error processing archive namecore-master/namecore_0.11-1_amd64.deb (--install):
 trying to overwrite '/usr/local/bin/test_bitcoin', which is also in package bitcoin
```

**Comment by domob1812** [comment]
Yes.  I wonder, however, why `test_bitcoin` is actually installed by the package at all.  I suppose it shouldn't, as it is a "private" unit test.

**Comment by unsystemizer** [comment]
I think I even used `--without-tests` in confugure.
I think I did the same on Bitcoin and it still built that (I never checked why, could be that it builds regardless of that setting).

**Comment by JeremyRand** [comment]
Can anyone confirm whether this is an upstream bug?

**Comment by unsystemizer** [comment]
I don't understand what you mean. 
Of course one cannot install the same package twice, so you'd see the same error message with Bitcoin Core (and by extension if I uninstalled Bitcoin Core prior to building this package I wouldn't have seen this error with Namecoin Core).

**Comment by JeremyRand** [comment]
Yes, the fact that the binary is named "test_bitcoin" is a bug in Namecoin Core.  The fact that it's built at all when tests are not desired, is possibly a bug upstream.

**Comment by unsystemizer** [comment]
I tested to see if tests are by some chance always installed, but there's no bug in Bitcoin Core. Could have been unclean make installed from who knows when or who knows what. I tried several times, twice with disabled, and once with "not disabled" (enabled) and in all 3 cases it was as expected.

**Comment by unsystemizer** [comment]
I built Namecoin Core `--without-tests`, so it appears that part needs to be changed (if we want people to be able to run Bitcoin Core & Namecoin Core with this functionality enabled)

**Comment by unsystemizer** [comment]
Can we close this? 
If anyone wants to update the code to 0.11.2, I can retest.

**Comment by JeremyRand** [comment]
@unsystemizer Does the current Namecoin Core code fix the issue of naming a binary "test_bitcoin"?

**Comment by unsystemizer** [comment]
Ugh, I mixed this up with https://github.com/namecoin/namecoin-core/issues/40. 
This I think hasn't been addressed yet, so unless there have been changes since Oct 3, this is still an issue.

**Comment by JeremyRand** [comment]
@unsystemizer Okay, we'll keep this open then.

**Comment by JeremyRand** [comment]
Has the test_bitcoin binary been properly renamed to test_namecoin?  Can anyone verify whether this bug is fixed?

**Comment by domob1812** [comment]
I think this should be have been fixed a long time ago.  Feel free to reopen if not.
