### ISSUE TITLE
Exporting names

### ISSUE THREAD

**Issue by somewhatnmc** [namecoin/namecoin-core#316]
Missing possibility of an export of all registered names with values. Suggested in #305 by @Tradefreak, continued here.

**Comment by JeremyRand** [comment]
We now have [C++ implementation of this](https://github.com/namecoin/namecoin-core/blob/e501d6f41ed1e96d9abc8aff55e91e453d80572c/src/qt/managenamespage.cpp#L237-L265), but we are missing the GUI button that actually triggers it.  Probably straightforward to add the button, though I have no clue if the C++ implementation actually works.
