### ISSUE TITLE
Missing newest release (0.18.1) files at https://www.namecoin.org/download/ 

### ISSUE THREAD

**Issue by 1000101** [namecoin/namecoin-core#326]
Newest release doesn't seem to be uploaded at https://www.namecoin.org/download/ (latest version is 0.18.1 but there is version 0.18.0 on the website)

**Comment by domob1812** [comment]
@JeremyRand can likely upload it.

**Comment by 1000101** [comment]
If @JeremyRand would be so kind, I would be most grateful. Thanks!

**Comment by 1000101** [comment]
The files for 0.18.1 are still missing.

**Comment by 1000101** [comment]
Please update the links, v 0.19.0 is already out :)

**Comment by JeremyRand** [comment]
@1000101 I built binaries of nc0.19.0 already (they're sitting on the Namecoin.org server), but apparently upstream Bitcoin Core had a critical bug in v0.19.0 and subsequently released v0.19.0.1, so I'm waiting for @domob1812 to tag nc0.19.0.1, and I'll build binaries of that tag for release.
