### ISSUE TITLE
name_show/name_history should support lookups by name hash

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#329]
**Is your feature request related to a problem? Please describe.**

Glenn is running an SPV client and wants to register `theintercept.bit`.  He first checks whether that domain is registered.  His SPV client sends that name to Keith's Namecoin Core instance via the `name_show` RPC method.  Unfortunately, this has revealed the name to Keith's Namecoin Core instance; Keith can now front-run the registration.

**Describe the solution you'd like**

`name_show` and `name_history` should allow looking up names by SHA256d hash.  This allows checking the existence of a name hash without revealing the preimage of nonexistent names.  This would require maintaining an index of hashes and preimages, but such an index is expected to be minimal in resource usage.

This would be done by adding an extra field `by_hash` to the `options` dict argument, which accepts a Boolean (false by default); if true, the supplied name is interpreted as a SHA256d hash instead of a preimage.

**Describe alternatives you've considered**

Currently, ElectrumX maintains its own name index (which indexes by hash).  This is wasteful since Namecoin Core already maintains most of that data.  Adding by-hash lookups to Namecoin Core would allow ElectrumX to remove its name index and simply pass through name lookup requests to Namecoin Core.  Also, the ElectrumX approach isn't useful for a hypothetical wire protocol analogue for `name_show`, whereas a Namecoin Core index would be applicable to a wire protocol command for looking up names.

I don't care strongly about what hash function is used; Bitcoin uses SHA256d for most things, so it seems like a safe choice.

**Comment by domob1812** [comment]
Sounds useful to me.  I have just a tiny suggestion for modification:  Instead of `by_hash` as boolean flag in the lookup options, what about a more general `namehash`?  For now, it would have the values `direct` (default) and `sha256d`.  But this way, we can support different hash types in the future if it seems useful.

**Comment by JeremyRand** [comment]
> I have just a tiny suggestion for modification: Instead of `by_hash` as boolean flag in the lookup options, what about a more general `namehash`? For now, it would have the values `direct` (default) and `sha256d`. But this way, we can support different hash types in the future if it seems useful.

ACK.

**Comment by yanmaani** [comment]
Can this be closed?

**Comment by domob1812** [comment]
Yes I think so.  Good catch!
