### ISSUE TITLE
Does it supports a UDF disc?

### ISSUE THREAD

**Issue by DaniellMesquita** [namecoin/namecoin-core#339]
When syncing bc, data isnt edited but just appends new?

**Comment by DaniellMesquita** [comment]
Emercoin works at same manner?

**Comment by domob1812** [comment]
This is not Emercoin but Namecoin.  When syncing (Bitcoin or Namecoin), there is both the general blockchain where data is just appended, but also a "current state" database (UTXO set and database of names), which is modified normally.
