### ISSUE TITLE
name_update for names in bech32 addresses

### ISSUE THREAD

**Issue by somewhatnmc** [namecoin/namecoin-core#340]
Is it desired behaviour that name_update of a name in a bech32 address does not send to a bech32 address if no destAddress option is given? Would it make sense to send to the same address type currently attached to the name?

**Comment by domob1812** [comment]
Currently, `name_update` (and other name operations) generate a new address of the configured default type.  This can be set to bech32 with `addresstype=bech32` in your `namecoin.conf` file.

I think that's exactly the purpose of a "default address type".  Having code that tries to find out what type the name was at and then use this would be an extra complication (especially considering that names might be at scripts that are no actual "address type"!).  Thus I think the current behaviour is probably the best.

**Comment by somewhatnmc** [comment]
makes sense.
