### ISSUE TITLE
name_show for bech32 addresses

### ISSUE THREAD

**Issue by Tradefreak** [namecoin/namecoin-core#343]
Currently in version 13.99 the command `name_show` gives out `<nonstandard>` for bech32 addresses, for example `name_show "d/speedup"`. Adding `addresstype=bech32` to the namecoin.conf file as mentioned in [issue #340](https://github.com/namecoin/namecoin-core/issues/340) doesn't resolve the problem. Configuration/update possible?

**Comment by domob1812** [comment]
Version 13.99 is ancient, it should work fine with a more recent one.

**Comment by Tradefreak** [comment]
This is the only one version at [https://www.namecoin.org/download/](https://www.namecoin.org/download/) for a long time already.
