### ISSUE TITLE
Missing command name_filter

### ISSUE THREAD

**Issue by Tradefreak** [namecoin/namecoin-core#344]
In the current Namecoin Core Qt v. 0.19.0.1 the command `name_filter` is missing! We had it in Namecoin Core Qt v. 0.13.99 with the additional "Manage names" tab. Please add this command (and occasionally the "Manage names" tab) ! Thx!

**Comment by domob1812** [comment]
This is an intentional change to streamline the RPC interface.  You can now use `name_scan` to do things that you did with `name_filter` before, plus things that were not even possible before.  See #269.

**Comment by domob1812** [comment]
I'm closing this for now, but feel free to reopen if there is any specific usecase that was possible before with `name_filter` and is no longer possible with `name_scan`.  Then I'll be happy to add it back in some form.

**Comment by Tradefreak** [comment]
@domob1812: Unfortunately I can't reopen an issue here, what anyone else closed. The `maxage` parameter is definitely missing, a workaround with the min. confirmations is not satisfactory! The clear definition of the maximal blocks is one of the most important parameters!

**Comment by domob1812** [comment]
Ok, that may be a valid point.  But I agree with Jeremy that you can just use the max/min confirmations.  If you don't think this works, then please provide us details why not.  So far both of us believe that this should be just an equivalent filter.

And in any case, Namecoin Core's name filtering is just meant to be a quick & easy way to get the list of names with some common filters.  You can quite easily and quickly use `name_scan` to go over the full list of names in a script and then apply whatever filtering logic you want yourself.
