### ISSUE TITLE
Missing maxage parameter

### ISSUE THREAD

**Issue by Tradefreak** [namecoin/namecoin-core#346]
As [mentioned in issue #344](https://github.com/namecoin/namecoin-core/issues/344#issuecomment-596059721) the `maxage` parameter is missing in the actual Namecoin Core Qt v. 0.19.0.1. One could wonder if the Namecoin dev team just don't want to provide any longer the possibility to filter out shortly expiring names, but anyway: This feature is needed, especially also for filtering out just active entries. Also I want to urge to implement the name tab again. As one can see in the peer lists, many users still use the 0.13.99 version, waiting already four years for an update! Thx!

**Comment by JeremyRand** [comment]
@Tradefreak You are abusing our issue tracker in multiple ways (e.g. posting multiple topics in a single issue, posting duplicate issues, spamming links to your own projects, and posting off-topic conspiracy theories about us).  Daniel has been very polite to you so far despite your abuse, but I am somewhat less tolerant of this conduct and I am tired of seeing this garbage in my GitHub notifications.  Consider this your last warning; if I see any additional abusive behavior from you, you may be banned from our issue tracker without any further notice.

Happy hacking.

**Comment by JeremyRand** [comment]
Also I'd really like to hear an explanation of why this use case is alleged to be unhandled by the `minConf` and `maxConf` arguments.

**Comment by Tradefreak** [comment]
I have no problem with it, I just reported a very relevant feature request here and as linked, Daniel himself advised to do so! You just have disqualified yourself as Namecoin developer, so it's finally time to say goodbye for you! Not only, that you pushed the whole project a big step back in the development, as you recommended to cancel the Open NIC support, you are also regularly refuse to solve issues, last but not least not to forget [this friendly welcome](https://github.com/namecoin/namecoin-core/issues/305#issuecomment-495722106)! The most funny fact is, that you claim to be the "Lead Namecoin Application Engineer", [but you not even know, who own's the main domain namecoin.bit](https://www.reddit.com/r/Namecoin/comments/ep43mk/why_no_namecoinbit_homepage/fizqn8j/)! I had to give you the proof first with reference to the transaction history on the blockchain! 🤣🤣🤣🤣🤣 And just for your information (and as info for the community): Namecoin is a community and peer to peer project, and nobody "owns" the blockchain and its services. Everyone can decide himself, which service to take or not to take!

And to get back to the topic: Of course the `minconf` and `maxconf` parameters can't give a defined filter of active/expired domains, this would be just a roughly approximate workaround not worth do discuss about! But be sure, that I surly won't discuss with you ever again! If Daniel, who maintains the Namecoin Core, wants to talk with me, he shall feel free to do so!

**Comment by JeremyRand** [comment]
> Of course the `minconf` and `maxconf` parameters can't give a defined filter of active/expired domains, this would be just a roughly approximate workaround

This certainly *sounds* like bullshit, but I'd be happy to hear why I might be wrong.

> not worth do discuss about!

Okay then.  OP isn't in any way obligated to provide details, but if they're not interested in providing the information needed to verify whether this issue is an actual bug, there's not much point in leaving this issue open.

Also locking this issue due to repeated abusive behavior from OP in this issue.
