### ISSUE TITLE
How to create a new address

### ISSUE THREAD

**Issue by DinoStray** [namecoin/namecoin-core#347]
Now I have the following utils:
bench_namecoin  namecoin-cli  namecoind  namecoin-tx
how to use them create a new nmc address?
BTW, I use testnet

**Comment by domob1812** [comment]
Make sure Namecoin Core itself is running (`namecoind -testnet`), then use `namecoin-cli -testnet getnewaddress`.

**Comment by DinoStray** [comment]
OK, it works
