### ISSUE TITLE
Any testnet explorer?

### ISSUE THREAD

**Issue by DinoStray** [namecoin/namecoin-core#349]
I can not find a valid nmc testnet explorer

**Comment by domob1812** [comment]
I doubt there is one, but this is not the right place to ask anyway.  Please try our [forum](https://forum.namecoin.org/) maybe.

**Comment by EthanHee** [comment]
@DinoStray hi, have you found a  a valid nmc testnet explorer now?   if  so,would you please tell me  ,thank you .
