### ISSUE TITLE
Put in a timebomb?

### ISSUE THREAD

**Issue by yanmaani** [namecoin/namecoin-core#359]
**Is your feature request related to a problem? Please describe.**  
There's a bunch of stuff that requires a hardfork that we would like to do. If Namecoin ends up blowing up on short notice, there's a risk that this becomes impossible, like with Bitcoin's block size hard fork controversy.

**Describe the solution you'd like**
If validation.cpp would be amended to always give an error for `nHeight > 600000`, we would be forced to hardfork by approximately 2022-03-01. That would reduce the future difficulty of convincing the ecosystem to go along with a hardfork, since they would have to update regardless. It seems comparatively easy to get the ecosystem to consent to such a timebomb right now, since there are no immediate effects.

**Describe alternatives you've considered**
The other option would be to not put one in, and hope that we have enough clout to convince people. If it remains a small project, it shouldn't be too hard, if it doesn't, it seems almost impossible.

**Comment by domob1812** [comment]
I'm not a big fan of that.  I don't really see how that helps with future changes that might be controversial, and it just puts in risk.  If we were to run into a controversial issue like the block size debate in Bitcoin, wouldn't this then just mean that most likely the community just agrees on a hard fork that removes the time bomb?  It would IMHO not really make it easier to go through with a controversial fork.  And if a fork is not controversial to begin with, I don't think we would have an issue to execute it anyway.

**Comment by yanmaani** [comment]
This is stupid, I have no idea why I ever proposed this.
