### ISSUE TITLE
namepsbt doesn't work in Qt GUI but namerawtransaction does

### ISSUE THREAD

**Issue by yanmaani** [namecoin/namecoin-core#367]
The following command gives a "TX decode failed (code -22)" error, as expected:  
`namerawtransaction "test" 0 {}`  
The following command gives a "Expected type number, got string (code -3)" error:  
`namepsbt "test" 0 {}`  
The `name_psbt.py` functional test passes.  

The problem persists whether I compile with GCC or Clang, so I don't think it's UB.  
If the code from `namerawtransaction` is copied into `namepsbt` verbatim, it still throws the error. The RPC methods' implementations look fine to me.

It somehow seems to be failing miserably in parsing its arguments, but I don't understand why it would differ from one method to the next. Alternatively, it could be PEBKAC.

**Comment by domob1812** [comment]
It is an oversight with the built-in RPC client (which is not used for the actual JSON-RPC interface and thus the functional test).  Will fix it today - thanks for reporting!

**Comment by domob1812** [comment]
Fixed in faeaef44867154e8d2c4296f98baef3d58f7fee1.
