### ISSUE TITLE
The "Manage Names" tab disappeared after Namecoin Core upgrade

### ISSUE THREAD

**Issue by Siemenskun** [namecoin/namecoin-core#370]
**Expected behavior**

There was "Manage Names" tab in previous versions.

**Actual behavior**

I've downloaded the client by the link https://www.namecoin.org/files/namecoin-core/namecoin-core-0.19.0.1/namecoin-0.19.0.1-win64-setup-unsigned.exe and installed it over previous installation. The "Manage Names" tab disappeared. Restart doesn't fix the issue.
![image](https://user-images.githubusercontent.com/32819735/94363489-18d67100-00cb-11eb-8c5b-c6cc1b321170.png)

**System information**

Windows 7 x64.

**Comment by domob1812** [comment]
This is expected, as the build with the names tab was always a beta and the feature has not yet been fully reviewed and merged to the production version unfortunately.  This is work in progress, though, and it is planned to finally get it all done and merged properly.  @JeremyRand can probably give more details about it and the expected timeline.
