### ISSUE TITLE
name_anyupdate value should be optional

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#372]
**Is your feature request related to a problem? Please describe.**

Always needing to specify a value when running `name_anyupdate` is annoying.  I might be registering a name without caring about its initial value, or I might be renewing a name without wanting to change the value.  We already support the latter use case in the GUI, but there is no such functionality in the RPC API, which makes the GUI code (which is harder to test) unnecessarily complex.

**Describe the solution you'd like**

The `value` parameter for `name_anyupdate` should be made optional.  In the case of `name_firstupdate`, a null `value` should be replaced with the empty string.  In the case of `name_update`, a null `value` should be replaced with whatever the value was in the name input.

**Describe alternatives you've considered**

We could continue to support this functionality exclusively in the GUI, but I don't really want to do that, because RPC code is easier to cover with integration tests, and some CLI/RPC users probably want this functionality too.

**Additional context**

N/A.

**Comment by JeremyRand** [comment]
@yanmaani is implementing this something you'd like to work on?

**Comment by domob1812** [comment]
Sounds good to me.  In principle this is something that the RPC client should care about, but if a simple change like this makes it easier for them (and the UI), why not.

**Comment by yanmaani** [comment]
I am, and it should probably indeed be a separate PR from deterministic salts.
