### ISSUE TITLE
Rename "Send"/"Receive" tabs

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#398]
**Is your feature request related to a problem? Please describe.**

Old versions of Bitcoin-Qt (e.g. 0.5.0) contained tabs named "Send coins" and "Receive coins".  See [this screenshot](https://i2.wp.com/www.nextofwindows.com/wp-content/uploads/2013/11/Screenshot_of_Bitcoin-qt.png?ssl=1).  This was the case for Namecoin-Qt 0.3.80 as well.  Current Bitcoin-Qt renamed those tabs to "Send" and "Receive".  While this renaming probably made sense for Bitcoin, I don't think it's ideal for Namecoin, because while Bitcoin's use cases are focused on "coins" (thus making the word "coins" redundant), Namecoin users are not as likely to automatically expect to be dealing with "coins".

**Describe the solution you'd like**

Rename the "Send" tab to "Send Coins", since it is explicitly focused on currency transactions.  Rename the "Receive" tab to "Receive Coins/Names", since it can be used for either purpose.

**Describe alternatives you've considered**

We could leave "Receive" as-is, but I think the vagueness of "Receive" is confusing, since users may be unsure whether they're supposed to use it to receive names, coins, or both.

**Additional context**

N/A.

**Comment by JeremyRand** [comment]
I'm happy to do a patch for this if there's a Concept ACK in this issue.

**Comment by domob1812** [comment]
ACK from me.  I think it is probably fairly obvious to users what "send" and "receive" refer to, but it doesn't hurt to make it more explicit.

**Comment by ultramassiveblackhole** [comment]
:+1:

**Comment by JeremyRand** [comment]
The tooltip for `Send` actually does say `Send coins`, so I think that one is fine as-is.  The tooltip for `Receive` says `Request payments`; I think changing that tooltip for `Request payments and name transfers` should be sufficient.
