### ISSUE TITLE
Conflict with Bitcoin Core's '/usr/local/include/bitcoinconsensus.h`

### ISSUE THREAD

**Issue by unsystemizer** [namecoin/namecoin-core#40]
There's another file which conflicts with Bitcoin Core.
This was built using `master` source dated Sep 7.

```
Selecting previously unselected package namecore.
(Reading database ... 147171 files and directories currently installed.)
Preparing to unpack namecore_0.11-1_armhf.deb ...
Unpacking namecore (0.11-1) ...
dpkg: error processing archive namecore_0.11-1_armhf.deb (--install):
 trying to overwrite '/usr/local/include/bitcoinconsensus.h', which is also in package bitcoin-0.11-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 namecore_0.11-1_armhf.deb
```

**Comment by phelixbtc** [comment]
If you like you could create a PR about this.

**Comment by unsystemizer** [comment]
I would if I knew what the fix is (a repo-wide S&R?) and how to do it :-)

**Comment by phelixbtc** [comment]
Ah, right, it is a bit more complicated than I thought. I can do it but would like to check with @domob1812 first: git move bitcoinconsensus.h/.cpp + S&R?

**Comment by domob1812** [comment]
I strongly prefer to avoid such things unless they are really needed.  But if this causes real issues when installing, that's of course such a reason. :)

Your suggestion sounds good.  Make sure to really use `git mv` instead of moving "outside of Git", though.

**Comment by phelixbtc** [comment]
@unsystemizer what exactly are you doing when you get the error? Maybe it would also be possible to change things so that the header is not installed globally. My Linux experience is lacking here...

**Comment by unsystemizer** [comment]
I have bitcoin-core 0.11 on this system.
I guess I could use a different `prefix` parameter to change the install location for the package (say, `prefix=/opt`) or not run Bitcoin Core on the same system. But if we wanted a solution that works for everyone regardless of their environment, `namecoinconcensus.h` seems like a good way.

**Comment by phelixbtc** [comment]
> I have bitcoin-core 0.11 on this system.
And now you simply try to install namecoin core if I understand correctly. OK, from my limited understanding it then seems we need to change it globally.

**Comment by unsystemizer** [comment]
Well, yes, we'd need to change it globally *unless* we want to document that as a known limitation (that it can't coexist with Bitcoin Core installed in default location unless `--prefix=` is used to build and install in separate location).

**Comment by phelixbtc** [comment]
@unsystemizer please check it out.

**Comment by unsystemizer** [comment]
Built from your fork (with these fixes included):
```
$ /usr/local/bin/namecoind --version
Namecoin Core Daemon version v0.11.99.0-gf25ff0f
Copyright (C) 2009-2015 The Bitcoin Core and Namecoin Developers
```

**Comment by phelixbtc** [comment]
Sweet. @domob1812 Please verify this is the proper way for smooth maintenance. I excluded docs but I just noticed I replaced it in a comment in one case.

**Comment by domob1812** [comment]
@phelixbtc:  Yes, looks good.
