### ISSUE TITLE
Make parentblock verbose if getblock verbosity >= 1

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#409]
**Is your feature request related to a problem? Please describe.**

`getblock`'s help text states that the `verbosity` field returns data in hex form when set to `0`, and in JSON form when set to `1`.  However, the `parentblock` field in `getblock` is not verbose (it's returned in hex form), even when verbose output is requested by setting verbosity to `1`.  This makes it more annoying for applications that want to analyze the parent block.  (In particular, some of the metrics code that I'm developing for Cyphrs is impacted by this.)

**Describe the solution you'd like**

If `verbosity` is at least `1`, the `parentblock` field should contain a JSON object.  The `hex` field of that JSON object should contain the hex header, and the other fields should correspond to the fields returned by `getblockheader` when `verbose` is `true` (except for the fields like `confirmations` and `mediantime` which depend on having a full chain instead of just a single header; those should be omitted).  The `height` field of the JSON object should be filled in by parsing the parent coinbase transaction as per BIP34.

**Describe alternatives you've considered**

I could try parsing the raw block in my application code, but that seems inconsistent with the motivation for having the `verbosity` option exist.

**Additional context**

N/A.

**Comment by domob1812** [comment]
Good catch.  Should be easy to fix, I'll look into it.
