### ISSUE TITLE
Transactions tab should identify name transfers

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#434]
**Is your feature request related to a problem? Please describe.**

The `Transactions` tab currently displays name transfers (both incoming and outgoing) as currency transactions.  This is confusing UX.

**Describe the solution you'd like**

* The `Transactions` tab should distinguish name transfers from currency transactions.
* The `Transactions` tab should distinguish name transfers from non-transfer name operations.
* The `Transactions` tab should distinguish incoming name transfers from outgoing name transfers.

**Describe alternatives you've considered**

N/A.

**Additional context**

N/A.

**Comment by domob1812** [comment]
Concept ACK

**Comment by JeremyRand** [comment]
@domob1812 Given a `interfaces::WalletTx`, what's the right way to determine whether a name is debited?  I don't see anything in that interface that would let me check the scriptPubKey of the inputs to determine which of them are name inputs.  Am I going to need to add something to the interface?

**Comment by JeremyRand** [comment]
(Will it be easier for Taproot transactions, since they include the name prefix in the signature preimage?)

**Comment by domob1812** [comment]
I'm not too familiar with that myself, but from a quick look it seems like `interfaces::WalletTx` is already meant to be "decoded" data.  So I'd say adding the information you need (perhaps `CNameScript` instances for each input or something like that) is what you should do.

**Comment by JeremyRand** [comment]
@domob1812 Ok.  Given that the interface includes a "credit" and "debit" field for currency, is it okay to add a "creditName" and "debitName", each containing an optional CNameScript?  That better fits the semantics of what my consumer code needs, and seems more consistent with the existing fields.

**Comment by domob1812** [comment]
@JeremyRand Yes, if that is all you need, then do that.
