### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by p3yot3** [namecoin/namecoin-core#44]
Got this error when compiling latest git on Ubuntu 64bit:

  CXX      libbitcoin_common_a-chainparams.o
chainparams.cpp: In constructor ‘CMainParams::CMainParams()’:
chainparams.cpp:130:76: error: expected ‘)’ before ‘;’ token
         vSeeds.push_back(CDNSSeedData("domob.eu", "seed.namecoin.domob.eu");
                                                                            ^
In file included from chainparams.cpp:15:0:
chainparamsseeds.h: At global scope:
chainparamsseeds.h:10:18: warning: ‘pnSeed6_main’ defined but not used [-Wunused-variable]
 static SeedSpec6 pnSeed6_main[] = {
                  ^
chainparamsseeds.h:892:18: warning: ‘pnSeed6_test’ defined but not used [-Wunused-variable]
 static SeedSpec6 pnSeed6_test[] = {
                  ^
make[2]: *** [libbitcoin_common_a-chainparams.o] Error 1
make[2]: Leaving directory `/home/rig/namecoin-core/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/rig/namecoin-core/src'
make: *** [all-recursive] Error 1
rig@rig:~/namecoin-core$

All previous compiled without issue using:

./configure --disable-tests --with-miniupnpc --without-gui

**Comment by domob1812** [comment]
Wow, that was quick - I only changed the code a few hours ago.  Do you always update to speedily or was this coincidence? :)  Anyway, should be fixed now.

**Comment by p3yot3** [comment]
Haha! Pure coincidence......Thanks for the quick fix - trying again now.
