### ISSUE TITLE
Fatal Compiling Error 

### ISSUE THREAD

**Issue by Gapcoin1** [namecoin/namecoin-core#475]
Compiling Namecoin-Core is broken

CXX      namecoind-bitcoind.o
In file included from ./netaddress.h:19:0,
                 from ./chainparams.h:11,
                 from bitcoind.cpp:10:
./util/strencodings.h:16:10: fatal error: charconv: Ingen sådan fil eller filkatalog
 #include <charconv>
          ^~~~~~~~~~
compilation terminated.
Makefile:12862: recipe for target 'namecoind-bitcoind.o' failed
make[2]: *** [namecoind-bitcoind.o] Error 1

Using 

Trisquel 9.0 OS

**Comment by domob1812** [comment]
Thanks for the report!  What version / commit are you trying to compile?  Also - can you try compiling the `bitcoin` branch (rather than `master`)?  This looks like it may be an issue with upstream Bitcoin rather than Namecoin specifically.

**Comment by Gapcoin1** [comment]
https://github.com/bitcoin/bitcoin/issues/23291


https://github.com/bitcoin/bitcoin/pull/23060


I have figured it out, sorry should have done a search first, but others might have this same issue as it was breaking a lot of Bitcoin Devs last 1 month ect......

Looks like it will no longer compile on Trisquel 9 OS, but Bitcoin and Namecoin didn't Compile on MX-Linux last time I tried but I will re-try under the new settings.....

Looks like compiling Bitcoin ect will become more difficult......there are instructions there but it seems gcc 8 is not good enough and Trisquel does not have higher gcc.......

Does everyone just use Ubuntu to Dev on?

**Comment by yanmaani** [comment]
> it seems gcc 8 is not good enough and Trisquel does not have higher gcc 

Latest Trisquel supports up to GCC 10. Try: `sudo apt-get install gcc-10`.

Anyway, if there is some issue with upstream Bitcoin, then this is not the right place for it. You should bring your issue to the Bitcoin community; we only maintain patches from upstream when necessary. Vote to close.
