### ISSUE TITLE
Pre-Register Domain by sending a Name_New

### ISSUE THREAD

**Issue by Stinger11** [namecoin/namecoin-core#496]
Hi,

I'm wondering if it is possible to pre-register a domain name that is currently active so that if the domain expires, you will potentially be first in line to register the domain?

I have heard that you can send a name_new to any active domain using Namecoin Core, but I've no idea how to go about this.

Any help would be much appreciated.

**Comment by domob1812** [comment]
Yes that's possible.  Not sure what the question here is about, you can just use `name_new` as you would normally.

**Comment by domob1812** [comment]
Also please note that this is not a support forum, so I'll close the issue.
