### ISSUE TITLE
Update GitHub repo metadata

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#502]
The GitHub repo metadata for Namecoin Core could use an update:

* Description: "Reimplementation" is probably obsolete language, since no one is using the old 0.3.80 release.  I'd suggest "Namecoin full node + wallet based on the current Bitcoin Core codebase."
* Website: https://www.namecoin.org/
* Topics: I'd suggest the following: `c-plus-plus cryptography namecoin p2p cryptocurrency security privacy blockchain anticensorship internet-freedom hacktoberfest human-rights free-speech civil-liberties namecoin-wallet decentralized`

**Comment by JeremyRand** [comment]
@domob1812 If the above details are okay, could you make the changes?

**Comment by domob1812** [comment]
Makes sense, done.  Thanks for the suggestion!
