### ISSUE TITLE
Release of 23.0

### ISSUE THREAD

**Issue by domob1812** [namecoin/namecoin-core#504]
Upstream Bitcoin Core recently tagged `v23.0`.  This is merged to Namecoin's `23.x` branch (commit 528bba5fe963404d627f29dcb2c5f61e450b66d0).

@JeremyRand (and everyone else):  Shall we tag Namecoin Core 23.0 from the same commit, or are there any extra changes or tests you want to do before that?

**Comment by JeremyRand** [comment]
@domob1812 If you'd like to tag it now, feel free.  We can always retag as `nc23.0.1` if release-blocker bugs are found.
