### ISSUE TITLE
sendrawtransaction can't be sent

### ISSUE THREAD

**Issue by nmcbtc** [namecoin/namecoin-core#513]
solved

**Comment by JeremyRand** [comment]
Looks like a escaping issue at first glance, but hard to know without seeing a verbatim copy of what you typed.

**Comment by nmcbtc** [comment]
What more needed? I have posted the exact commands above. :roll_eyes:

**Comment by nmcbtc** [comment]
@JeremyRand the issue arisen when tried to send a name_firstupdate similar to the transaction below. The transaction below is sent and **locked name_firstupdate** in block `613533`. 

The transaction included in block `613535` with the well known value of `BM-2cXeN1HuY8h7nYAkPj1mny4Ki4wywPorwM`

`./namecoin-cli decoderawtransaction` 00710000000102cdeae08127bb20d158d4d2a4813540d45463a824cba4b52d2723835d486ab3f1000000006a47304402203913bbf2fcdbb12a81d4f666566cfad66cd2e61987be4de59f8c72a4b8d356e1022075a13bb6ba70a1d608b2fea062c530fda88557d1670796249c9e08c0e11a32e70121027f91e77579444a9e22d25e8cae33e253cb289a889f84727330da24257975fd8ffeffffff1e912632f785a52aaf3719836a3c38a09d8ab0596c26063c7e6df6020b59508f0100000000feffffff0220b71d0100000000160014fd1ca00e2205a10db9a3e15628fd8a7df571119940420f000000000065520d642f65617379626974636f696e143afc9470219e3a1221cf05001e8d4b893b67644025424d2d326358654e314875593868376e59416b506a316d6e79344b6934777977506f72774d6d6d76a9149c270a9dfd1e3c4647b26118b658ad38e128d83788ac000247304402203859f5cffb46485ceae84f4fa84ee19e47289cc761d23f88cc6bf04e6601b195022056ad641a4ae7e6858619ad35c6ba5596733d40fbb90729adf5915e7ad1812d2f0121027da7d6b23244ebfa4b2d66b253acb68b0eb0fb2cc8794a5c7d72f992169c0ce99d5c0900
```
{
  "txid": "766483454fb1d19367131fbdd10c99d61647bb8531623abb21e09111ad5920dd",
  "hash": "2e1cb1076bab81c4a21cbc24ed8ea00ae78ad2c11b70ccb922762faac6236875",
  "version": 28928,
  "size": 449,
  "vsize": 367,
  "locktime": 613533,
  "vin": [
    {
      "txid": "f1b36a485d8323272db5a4cb24a86354d4403581a4d2d458d120bb2781e0eacd",
      "vout": 0,
      "scriptSig": {
        "asm": "304402203913bbf2fcdbb12a81d4f666566cfad66cd2e61987be4de59f8c72a4b8d356e1022075a13bb6ba70a1d608b2fea062c530fda88557d1670796249c9e08c0e11a32e7[ALL] 027f91e77579444a9e22d25e8cae33e253cb289a889f84727330da24257975fd8f",
        "hex": "47304402203913bbf2fcdbb12a81d4f666566cfad66cd2e61987be4de59f8c72a4b8d356e1022075a13bb6ba70a1d608b2fea062c530fda88557d1670796249c9e08c0e11a32e70121027f91e77579444a9e22d25e8cae33e253cb289a889f84727330da24257975fd8f"
      },
      "sequence": 4294967294
    },
    {
      "txid": "8f50590b02f66d7e3c06266c59b08a9da0383c6a831937af2aa585f73226911e",
      "vout": 1,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "txinwitness": [
        "304402203859f5cffb46485ceae84f4fa84ee19e47289cc761d23f88cc6bf04e6601b195022056ad641a4ae7e6858619ad35c6ba5596733d40fbb90729adf5915e7ad1812d2f01",
        "027da7d6b23244ebfa4b2d66b253acb68b0eb0fb2cc8794a5c7d72f992169c0ce9"
      ],
      "sequence": 4294967294
    }
  ],
  "vout": [
    {
      "value": 0.18724640,
      "n": 0,
      "scriptPubKey": {
        "asm": "0 fd1ca00e2205a10db9a3e15628fd8a7df5711199",
        "hex": "0014fd1ca00e2205a10db9a3e15628fd8a7df5711199",
        "reqSigs": 1,
        "type": "witness_v0_keyhash",
        "addresses": [
          "nc1ql5w2qr3zqkssmwdru9tz3lv20h6hzyve6xd2sj"
        ]
      }
    },
    {
      "value": 0.01000000,
      "n": 1,
      "scriptPubKey": {
        "nameOp": {
          "op": "name_firstupdate",
          "name": "d/easybitcoin",
          "value": "BM-2cXeN1HuY8h7nYAkPj1mny4Ki4wywPorwM",
          "rand": "3afc9470219e3a1221cf05001e8d4b893b676440"
        },
        "asm": "OP_NAME_FIRSTUPDATE 642f65617379626974636f696e 3afc9470219e3a1221cf05001e8d4b893b676440 424d2d326358654e314875593868376e59416b506a316d6e79344b6934777977506f72774d OP_2DROP OP_2DROP OP_DUP OP_HASH160 9c270a9dfd1e3c4647b26118b658ad38e128d837 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "520d642f65617379626974636f696e143afc9470219e3a1221cf05001e8d4b893b67644025424d2d326358654e314875593868376e59416b506a316d6e79344b6934777977506f72774d6d6d76a9149c270a9dfd1e3c4647b26118b658ad38e128d83788ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "NAp2PDq95hzFEEa6PAG52nGYAk3592C8Gu"
        ]
      }
    }
  ]
}
```

**Comment by nmcbtc** [comment]
The exact same thing happened in transaction **aa0b64be95438c008965bf7aa721f7638bf195bfcf919b09761b1f29f4f5b588** https://namebrow.se/tx/aa0b64be95438c008965bf7aa721f7638bf195bfcf919b09761b1f29f4f5b588/

**BM-2cXeN1HuY8h7nYAkPj1mny4Ki4wywPorwM** clearly squatting and abusing mempool. 

Namecoin Core should reject first_nameupdate to be locked before the domain expires.

**Comment by JeremyRand** [comment]
...it took me several re-reads to infer that you're talking (I think?) about rejecting `name_new` outputs for names that currently exist...?  If that's what you're asking for, you might want to (1) make that more obvious, and (2) explain why you think that's possible+desirable.  Also I don't see what this has to do with whatever error code you posted in OP.

**Comment by nmcbtc** [comment]
I have tried to produce a rawtransaction with `first_nameupdate` and lock it but the `sendrawtransaction` doesn't even work, as described above. 

`name_new` can be sent anytime and that's okay, the problem is when `first_nameupdate` getting locked before the name expires. There is no chance of competing with such a transaction, no matter how fast you relay your `first_nameupdate` the locked transaction gets included in the next block after the desired name expires. 

I propose removing the locking function from Namecoin Core and with this giving a chance to compete for the expiring name for everyone. This particular squatter in this way by creating locked `first_nameupdate` was able to obtain `11,319` names.

**Comment by nmcbtc** [comment]
On the other hand is interesting how this person can use `sendrawtransaction` when it doesn't work. You can create a raw transaction and able to sign it but you unable to send it.
