### ISSUE TITLE
CRITICAL! A severe bug caused name loss!

### ISSUE THREAD

**Issue by ghost** [namecoin/namecoin-core#524]
@JeremyRand

Daniel Kraft @domob1812's commit https://github.com/namecoin/namecoin-core/pull/220 causing a critical bug which **resulting name loss!** 

If you transfer a so-called "non-standard" name in Namecoin-QT, you will lose your name!

Example name: `&#/transferthis
`
If you try to transfer Example name to another address, it will issue a `name_update` but never transfer the name; instead, it will transfer 0.01 NMC to the address where the name should be transferred.

The name will never appear in the other wallet! This confirmed with `name_list`!

Checking it with `name_show` returns the new address, but you cannot transfer because it is technically not in your wallet!

As a result, the name is ~~irreversibly~~ lost!

**Comment by JeremyRand** [comment]
Can you provide exact steps to reproduce, including the exact contents of the `name_update` command you entered?  (Was this done with `namecoin-cli` or in the GUI console window?)

**Comment by JeremyRand** [comment]
Also please provide the exact Git commits you tested that do and do not have this bug.

**Comment by JeremyRand** [comment]
Until you cooperate with our investigation by telling us exactly what commands you typed (both the `name_update` and `name_show`), there is not much we can do.  We're not psychic, we can't reliably guess what you did to trigger this bug.

**Comment by JeremyRand** [comment]
I mean, this certainly *looks* like OP is just incompetent, but since OP is refusing to assist in reproducing this bug, I guess we'll never know unless someone else can reproduce it.  This bug will remain closed until/unless that occur.
