### ISSUE TITLE
v. 22.0.0 hanging at "Connecting to peers" 

### ISSUE THREAD

**Issue by noospheer** [namecoin/namecoin-core#539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

"Connecting to peers..."

### Expected behaviour

Should connect and sync

### Steps to reproduce

Namecoin Core v. 22.2.0
Qt 5.12.11
Ubuntu 22

Extracted the tar ball and ran `./namecoin-qt` in terminal

First time running.

UI says "Connecting to peers..." forever

### How did you obtain Bitcoin Core

Other

### What version of Bitcoin Core are you using?

NMC Core 22.2.0, Qt 5.12.11

### Operating system and version

Ubuntu 22

**Comment by noospheer** [comment]
bump

**Comment by JeremyRand** [comment]
Fixed by https://github.com/namecoin/namecoin-core/pull/500. Please open a new issue if you still have connectivity issues.
