### ISSUE TITLE
IDN

### ISSUE THREAD

**Issue by rq4w7z** [namecoin/namecoin-core#540]
### Please describe the feature you'd like to see added.

When Internationalized Domain Names will be available?

**Comment by domob1812** [comment]
The spec for the `d/` namespace already provides support for IDN.  Namecoin Core is not a resolver, so not sure what exactly you mean by this.  Is this about support in the Qt frontend specifically?

**Comment by JeremyRand** [comment]
Superseded by https://github.com/namecoin/namecoin-core/issues/542
