### ISSUE TITLE
namecoin-qt.exe icon is very low-res

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#56]
Steps to Reproduce: build Bitcoin Core and Namecoin Core for Windows with Gitian.  Extract the 64-bit zips onto a Windows 10 machine.  Go to the bin folders in Windows Explorer.  Click "View" --> "Extra large icons".

Expected results: bitcoin-qt.exe and namecoin-qt.exe should have similarly high-quality icons displayed.

Observed results: namecoin-qt.exe's icon is very small and low-resolution compared to bitcoin-qt.exe's icon.

Note that right now Namecoin Core master branch doesn't build for Windows in Gitian; I will submit a PR for that soon. So, it may be difficult to reproduce this issue for Windows right now.
- [x]  master branch
- [ ]  0.12 branch

**Comment by JeremyRand** [comment]
This still needs to be backported to the 0.12 branch, but I'm okay with deferring that until the nc0.12.2 milestone.  Any objections to deferring it until then?

**Comment by JeremyRand** [comment]
> This still needs to be backported to the 0.12 branch, but I'm okay with deferring that until the nc0.12.2 milestone. Any objections to deferring it until then?

@domob1812 ?

**Comment by domob1812** [comment]
I'm fine either way, so let's defer it.

**Comment by JeremyRand** [comment]
Okay, this ticket is now deferred to nc0.12.2 milestone.

**Comment by JeremyRand** [comment]
Closing since this fix is in the 0.13 branch, and the 0.12 branch isn't in use anymore.
