### ISSUE TITLE
0.12 branch has wrong Linux Gitian descriptor version

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#57]
The 0.12 branch's Linux Gitian descriptor name is version 0.10.  https://github.com/namecoin/namecoin-core/blob/0.12/contrib/gitian-descriptors/gitian-linux.yml#L2 .  It should be 0.12.

Is it okay if I submit a PR which fixes this in the 0.12 branch?

**Comment by domob1812** [comment]
Yes, definitely.  Thanks!

**Comment by JeremyRand** [comment]
This is fixed, closing.
