### ISSUE TITLE
Getting segfault when starting namecoind

### ISSUE THREAD

**Issue by halvors** [namecoin/namecoin-core#59]
Hi.

I'm getting a segfault when running namecoind.

Here  is a gdb output: http://pastebin.com/yF4Zh4VX
Crash i get at startup: http://pastebin.com/mA8w3N8b

Hope this issue can be resolved as soon as possible :)

**Comment by domob1812** [comment]
Interesting!  Is this the latest version from Git (where I pushed some upstream merges just this weekend)?  Also, can you please run a "bt" (backtrace) in GDB as well?  The current output does not give me a lot of information unfortunately.  Thanks for your help!

**Comment by halvors** [comment]
Here is a GDB output with backtrace: http://pastebin.com/zg0gP7sv

**Comment by halvors** [comment]
I've compiled from commits from October, November and Desember, all of them is throwing segfault for me.

**Comment by domob1812** [comment]
Thanks!  The backtrace looks strange to me.  Are you sure there is no other problem with your system or the build in any way?  Can someone reproduce that?

**Comment by halvors** [comment]
Well. I've followed the guide on how to compile bitcoin: https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md

Yeah i know that's for bitcoin, but it's very very similar on the dependency front right?

I've installed the needed libraries, the build run just fine.

**Comment by halvors** [comment]
I've produced this on Ubuntu Server 15.10. On both a physical machine and a virtual machine. Same issue on both setups.

**Comment by halvors** [comment]
@domob1812 Any idea how to fix this?

**Comment by domob1812** [comment]
Not yet, unfortunately.  It may be related to the somewhat recent OS - anyone else having experience on Ubuntu 15.10?

**Comment by fsb4000** [comment]
@halvors 
Hi. I tested Ubuntu Server 15.10 today.
Namecoind works fine.
I use this iso:
http://releases.ubuntu.com/wily/ubuntu-15.10-server-amd64.iso

I install ubuntu 15.10 with default setting and enter some command:
```
sudo apt-get install git build-essential libboost-dev libboost-system-dev libzmq3-dev \
 libboost-filesystem-dev libboost-test-dev libboost-program-options-dev libboost-thread-dev   \
 libssl-dev libdb++-dev libqrencode-dev libevent-dev bsdmainutils libtool autotools-dev automake pkg-config 
```
```
git clone https://github.com/namecoin/namecoin-core.git
cd namecoin-core
./autogen.sh
./configure --with-incompatible-bdb
make
strip src/namecoind
strip src/namecoin-cli
strip src/namecoin-tx
```
I think you have segfault because use  db4.8 from ppa:bitcoin/bitcoin because it builds with gcc 4 and Ubuntu 15.10 has gcc 5. But this is just my guess.
If needed I can upload Virtual Box machine with Ubuntu 15.10 and compiled namecoin.

**Comment by JeremyRand** [comment]
@halvors Do you get the same problem when building Bitcoin Core?  I'm
curious if this is specific to Namecoin.

@fsb4000 Thanks for testing.  Using a current bdb package will result in a
Namecoin Core binary that *looks* fine, but which silently upgrades any
wallet.dat file that it touches to a format that official releases can't
read.  Recovering such a wallet is unpleasantly difficult for novices.  For
this reason, it's a good idea to either build with Gitian, or do a depends
build.  Info on doing a depends build is at
https://forum.namecoin.org/viewtopic.php?f=8&t=2347 (thanks to moa for
posting the instructions).

**Comment by halvors** [comment]
@fsb4000 You where right. The problem was the BerkelyDB that ships with the bitcoin ppa.

Building it from source solved the problem for me, thank you very much.

@domob1812 Think we can close this issue. :+1:

**Comment by JeremyRand** [comment]
Before we close this, can anyone verify whether the same behavior occurs
with Bitcoin Core?  If so, that's a bug in the build instructions that we
should probably report upstream.

**Comment by fsb4000** [comment]
@JeremyRand 
I tested and I didn't get such behavior.
```
sudo apt-get remove libdb++-dev
sudo apt-get autoremove
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev
git clone https://github.com/bitcoin/bitcoin
cd bitcoin
./autogen.sh
./configure
make
strip src/bitcoind
strip src/bitcoin-cli
cd src
./bitcoind -daemon=1
./bitcoin-cli getinfo
```
![bitcoin](http://i.imgur.com/o5gGdS7.png)
Now I will test namecoin with libdb 4.8 from ppa:bitcoin/bitcoin
