### ISSUE TITLE
Tag a release candidate for 0.12

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#63]
Bitcoin has already tagged 2 release candidates for the 0.12 branch; it would be great if we can tag an rc.  Wang Chun from F2Pool inquired about this recently.  Among other things, tagging a release candidate would be useful for testing the release process all the way through, and it would allow us to release Gitian binaries so that we can get more testers.  A lot of people are still on either old 0.11.99 builds or 0.3.80 because we haven't put out newer binaries.

**Comment by JeremyRand** [comment]
@domob1812 Are you able to do this?

**Comment by domob1812** [comment]
Yeah, I can do it.  The only question is, should I just tag a "random" snapshot of 0.12 (like the current one)?  Or maybe we should wait for Bitcoin to officially release 0.12 - should not be too long?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On 02/10/2016 11:37 AM, Daniel Kraft wrote:
> Yeah, I can do it. The only question is, should I just tag a
> "random" snapshot of 0.12 (like the current one)? Or maybe we
> should wait for Bitcoin to officially release 0.12 - should not be
> too long?

My opinion is that we should start tagging release candidates as soon
as Bitcoin upstream does so.  This appears to be the opinion of F2Pool
as well.  So yes, using the current state of the 0.12 branch seems
acceptable for a tagged release candidate.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWvFGtAAoJEAHN/EbZ1y06TOUP/2KDPsILiIfrOV7RMhwomzNt
eupXWRJFZpqI/Fx/hiq1Rl4Dg7nUK2yw556RJ0MszJw0c5E0G0jqJVhAiRD6DdeG
bZN9DKEWqB1Uyt6B+Utty7UT5zoG2CL1kNjDIqdBU4Q7tlJ7tOsL1ouT2W7dyMbD
/rxo92k47pw6Y/5kNBgovuX7vu043vZneHqijF2FLOtlL0BTYsVVK2BhUg3EfYCq
8jT9wIFAgRFCKsXQhoSZadecDU92hihjc8XqODu39fmboUfyFrcrJm6UMlZQkQyE
9Nuy2VTH1AZUqIgyi1ngZQcbNm3BTviTW6AWpfZ9ji0D5lgGk//0Kt2nMe3NutvX
RKavj+8aHHR8nQlL0DV9ImaoyhSHCQIpgWKN/gH2nbFDcgx0Ti/cLstOb9C/O5os
jjbaFgGwcNQbp4lf9iRRjU4nFm5ukB/EE0sXD/u5iH2ALEPSRTQK2cI6UrBWsVzE
p83UuAcYKheVJVlaCQ9Tnw16iIumlUZLOkXpdAhzxqrfNdOAaALYuXkafbwsBirW
r3KZannq2ERgKrvNs0MsYvb3QgrruBfCEakZINa/7P8b0poSS0YomQZQwLlhl5YY
vm1oEa+uL6N+d9SrGlOH2skg6yrtMz9TFUIHKXokl38j4gKVAYCQr9s6El+DYTjL
NmE2dUyH2TD213/ahkPd
=wa58
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
Done: https://github.com/namecoin/namecoin-core/releases/tag/nc0.12.0rc1
