### ISSUE TITLE
Please start tagging releases.

### ISSUE THREAD

**Issue by halvors** [namecoin/namecoin-core#65]
Please start tagging releases. When compiling from source i con't know witch commit is considred stable or not.

**Comment by domob1812** [comment]
We just did this for https://github.com/namecoin/namecoin-core/issues/63.  The tag is `nc0.12.0rc1`.

**Comment by halvors** [comment]
Yeah, but could you please tag the previous version as well? :)

**Comment by domob1812** [comment]
Which previous version?  This is the first "official" tag on the new Namecoin Core.  (I agree that we should have done that earlier, but I always was targetting "the next Bitcoin release".)  The previous version is the now-almost-defunct 0.3.80.
