### ISSUE TITLE
Rename repo to 'namecoin-core'

### ISSUE THREAD

**Issue by indolering** [namecoin/namecoin-core#7]
*Migrating discussion from [forum thread](https://forum.namecoin.info/viewtopic.php?f=8&t=2176).*

@JeremyRand and Indoling have voiced support for changing the name of this repo from `namecore` to `namecoin-core`.

The "namecore" name does not follow Bitcoin's "Bitcoin Core" naming convention and also represents a potential naming collision with the Bitcore JS library.  This name change should happen ASAP before the repo gains widespread use.

**Comment by JeremyRand** [comment]
Can we close this now?

**Comment by JeremyRand** [comment]
I think this is resolved, closing.
