### ISSUE TITLE
Did the nc tags disappear?

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#70]
GitHub isn't showing the "nc" tags for me (neither rc1 nor rc2).  Did they inadvertently get removed somehow?

**Comment by josephbisch** [comment]
Check if they're still missing. I see them on GitHub.

**Comment by JeremyRand** [comment]
From https://github.com/namecoin/namecoin-core , I click on the dropdown that says "Branch: master", I then click on "tags" and type "nc" into the search box; I get no results.  Is there some other procedure I'm supposed to follow?  :/

**Comment by josephbisch** [comment]
Click releases on the bar that also has commits, branches, contributors. I don't know why it's missing from where you are looking, but it is missing for me too.

**Comment by JeremyRand** [comment]
Interesting.  I confirm that it shows up fine under the Releases tab.  I wonder why there's an inconsistency, maybe a GitHub bug?
