### ISSUE TITLE
undefined reference toCMerkleTx::ABANDON_HASH

### ISSUE THREAD

**Issue by santzi** [namecoin/namecoin-core#71]
Hi,

I downloaded the latest source codes from master branch and got compile error for a while.
./autogen.sh
./configure --disable-wallet --without-gui
make -j2

"libbitcoin_common.a(libbitcoin_common_a-auxpow.o): In function operator==': /home/jeppa/Downloads/git/namecoin-core/src/./uint256.h:45: undefined reference toCMerkleTx::ABANDON_HASH'
collect2: error: ld returned 1 exit status
make[2]: *** [namecoind] Error 1"

I have compiled BTC/LTC and other daemons without problems.
This is quite strange error.

**Comment by santzi** [comment]
Problem solved:
./autogen.sh
./configure --without-gui
make -j2

Do not use "./configure --disable-wallet --without-gui"

**Comment by domob1812** [comment]
I'm glad that you solved the issue yourself, but this is actually still a bug - building without wallet should work.  I will fix this soon, which should only require moving the definition of `ABANDON_HASH` from wallet.cpp to auxpow.cpp.  Thanks for raising this issue!

**Comment by JeremyRand** [comment]
Reopening since there's an underlying issue.  @domob1812 feel free to close again once the issue is fixed.

**Comment by domob1812** [comment]
Thanks, but I've already fixed that. :)
