### ISSUE TITLE
Release Process documentation is still for Bitcoin

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#73]
The Release Process documentation still lists Bitcoin instructions.  While these are easy to mentally convert to Namecoin instructions for people who are familiar with Gitian usage, I think it would be useful to explicitly change the relevant instructions to apply to Namecoin.  I've already seen one person report issues because the documentation was unclear, and even for people who can mentally convert, I think decreasing cognitive load is a good thing.

Any objections if I submit a PR to fix this?

- [x]  master branch
- [x]  0.12 branch

**Comment by domob1812** [comment]
A PR is definitely welcome.  In case this introduces merge conflicts in the future, I will simply keep the Namecoin version; so if something changes substantially, it is up to you or others to keep the Namecoin version up-to-date.  Apart from that, however, I see no issues and think this helps.

**Comment by JeremyRand** [comment]
@domob1812 I'm fine with resolving merge conflicts for this, going forward, as long as you let me know when merge conflicts are encountered.  I'm unlikely to notice otherwise, until I try to build a release tag, which would be kind of awkward.  :)

**Comment by domob1812** [comment]
Ok, sounds good.  Just go ahead and submit a PR.  I will try to remember pinging you in case there are any merge conflicts that I can not trivially resolve. :)

**Comment by JeremyRand** [comment]
This is fixed now.
