### ISSUE TITLE
testscript txn_clone.py fails

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#76]
See https://travis-ci.org/namecoin/namecoin-core/jobs/117099590#L5578 for a log of the failure.  It occurs on all Travis CI tests that utilize txn_clone.py, and appears to be the cause of all of our current Travis CI failures on the master branch.  It doesn't happen on the auxpow branch, which suggests something Namecoin-specific is causing it.  It also doesn't happen on the 0.12 branch.

**Comment by domob1812** [comment]
Thanks for spotting!  It was easy to fix and should work now.  The same underlying "issue" (`createrawtransaction` does not allow specifying the locktime without a nameop) is also present in 0.12, but there the test does not make use of that.  I will fix it there nevertheless as well.

**Comment by domob1812** [comment]
Backported to 0.12.

**Comment by JeremyRand** [comment]
Thanks, I confirm that the issue appears to be resolved now.  (Sadly there are now a couple of new errors that happen after this point; I'll file issues about those.)
