### ISSUE TITLE
testscript abandonconflict.py is failing

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#77]
The only Travis CI instance in the master branch which executes abandonconflict.py fails with the below error.  This is the "32-bit + dash" Travis CI instance, if it matters.  The "32-bit + dash" instance in the 0.12 branch fails for a different reason (before it gets to that point), but the "bitcoind" instance in the 0.12 branch does execute it successfully, so this issue is probably specific to the master branch.

Running testscript [1mabandonconflict.py[0m ...
Initializing test directory /tmp/testZdwBcB
start_node: namecoind started, calling namecoin-cli -rpcwait getblockcount
start_node: calling namecoin-cli -rpcwait getblockcount returned
start_node: namecoind started, calling namecoin-cli -rpcwait getblockcount
start_node: calling namecoin-cli -rpcwait getblockcount returned
start_node: namecoind started, calling namecoin-cli -rpcwait getblockcount
start_node: calling namecoin-cli -rpcwait getblockcount returned
Assertion failed: 
  File "/home/travis/build/namecoin/namecoin-core/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/test_framework/test_framework.py", line 146, in main
    self.run_test()
  File "/home/travis/build/namecoin/namecoin-core/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/abandonconflict.py", line 80, in run_test
    assert(len(self.nodes[0].getrawmempool()) == 0)
Stopping nodes
Cleaning up
Failed
Traceback (most recent call last):
  File "qa/pull-tester/rpc-tests.py", line 283, in <module>
    runtests()
  File "qa/pull-tester/rpc-tests.py", line 183, in runtests
    rpcTestDir + testScripts[i] + flags, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/travis/build/namecoin/namecoin-core/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/abandonconflict.py --srcdir /home/travis/build/namecoin/namecoin-core/bitcoin-i686-pc-linux-gnu/src --coveragedir /tmp/coverageoBSGou ' returned non-zero exit status 1

**Comment by domob1812** [comment]
Incidentally, I just fixed this (at least I think - we'll have to see how Travis-CI reports it later) with the latest upstream merge.  The issue was related to the different fee policies between Namecoin and Bitcoin.  (Unfortunately, quite a few regression tests depend on the default fee settings and policies.)

Let's keep this open until Travis-CI shows that the issue is really fixed, but I hope it is. :)

**Comment by JeremyRand** [comment]
Unfortunately I can't confirm whether this is fixed, because there's a new failure https://github.com/namecoin/namecoin-core/issues/79 which shows up before this test runs.  So, leaving this one open for now.

**Comment by JeremyRand** [comment]
Confirmed fixed in the "bitcoind" instance.  Thanks for the fix.  Closing.
