### ISSUE TITLE
Time skew warning popup refers to "Bitcoin Core", should be "Namecoin Core"

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#85]
I ran into this back in January 2016; I don't think it's been fixed yet.  To reproduce, change your system clock to be substantially offset from actual time (I think I did something like 12 hours off).  Namecoin-Qt will then generate a popup much like the attached screenshot.

![namecoincoreguibug](https://cloud.githubusercontent.com/assets/244188/14245367/67c372bc-fa50-11e5-8821-46219d73df31.png)

Note that the error refers to "Bitcoin Core"; it should say "Namecoin Core".  I guess we missed this string when we were rebranding.

The test was done on Windows 10 x64, but I assume similar results will occur on other OS's.

**Comment by JeremyRand** [comment]
@fsb4000 is this something you might be interested in looking at?

**Comment by domob1812** [comment]
This is presumably fixed now.  This is the place where the message is produced: https://github.com/namecoin/namecoin-core/blob/ea7d6553bc7d5660cb2f90f1642b6d7f57d8bf77/src/timedata.cpp#L104

Note how it uses `PACKAGE_NAME`.
