### ISSUE TITLE
bip68-112-113-p2p.py failing on master and auxpow branches

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#86]
Error occurs on "32-bit + dash" and "bitcoind" build instances of both the master and auxpow branches.  These are the only instances that attempt to run that test; no instances run this test successfully in either master or auxpow.

Error log at https://travis-ci.org/namecoin/namecoin-core/jobs/120430069#L5435 .

Apparently introduced in this build: https://travis-ci.org/namecoin/namecoin-core/builds/120430063

**Comment by JeremyRand** [comment]
@domob1812 any idea what might be wrong here?

**Comment by domob1812** [comment]
Not really - but probably just because BIP9 is not active for now.

**Comment by JeremyRand** [comment]
Do I understand correctly that this test is solely intended to test functionality that is intentionally disabled on the Namecoin network?  Given that this test failure makes it more difficult to determine if other tests are failing, I think this should be fixed, even if it's a harmless indication of BIP9 not being activated.  Is the best solution to simply disable this test from running until BIP9 is activated?  Or is there a better way?

**Comment by domob1812** [comment]
I'm not 100% sure that the test is not able to work with the current settings vs. something is broken that could in theory be fixed even without enabling BIP9 for Namecoin.  But yes, this is only about functionality that is not supposed to be active in Namecoin for now.  If you agree, I will disable the test for now.

**Comment by JeremyRand** [comment]
> I'm not 100% sure that the test is not able to work with the current settings vs. something is broken that could in theory be fixed even without enabling BIP9 for Namecoin. But yes, this is only about functionality that is not supposed to be active in Namecoin for now. If you agree, I will disable the test for now.

Yes, I'm fine with disabling the test for now.  We should create another ticket (in a milestone post-hardfork) for re-enabling it.

**Comment by domob1812** [comment]
Disabled the test.

**Comment by JeremyRand** [comment]
Appears to be fixed; closing.
