### ISSUE TITLE
Problem after encrypting wallet

### ISSUE THREAD

**Issue by lukavia** [namecoin/namecoin-core#89]
Hi, I have a serious problem after encrypting my wallet. I can not use it anymore. When I try to change the password or issue walletpassphrase I get and error that the key is incorrect: 
code: -14, Error: The wallet passphrase entered was incorrect. 

For the first couple of days I though that I've managed to enter the password incorrectly twice and spend a lot of time trying to figure out was could I have mistyped, but since I was very careful entering the password I start to search for another issue. 

I have an unencrypted backup from a several months back and tried the procedure of encrypting the wallet again, this time using the same paste from a copy for both encrypting and then trying to unlock it. 
Meaning I'm doing: 
1. Coping my password to clipboard. 
2. Choose Encrypt Wallet option from menu. 
3. Paste in both fields the password (visually verify the length)
4. After the namecoin close, I start it again. 
5. Choose change password from the menu and use the same paste (not a new copy) for the old password field. 
6. Enter 1 for both fields for the new password. 
7. Use console to try to unlock the wallet. 
And the result is the same: error code -14. 

Now if I close the program, delete the wallet.dat and perform the same steps above with an empty wallet it works OK, and I can change the password with no problem. 

I have tested with behaviour several times on a Mac and ubuntu 14.04 using version 0.3.80 and this bug is reproducible only with my wallet. 

So obviously the problem is in my wallet, but I have no idea how to resolve it and recover the encrypted wallet. I'm missing 3 names from my last backup. 

I've used pywallet script from https://raw.githubusercontent.com/dlitz/pywallet/master/pywallet.py to have a dump on the wallet and see it is there and it is encrypted, but I don't see a way to decrypt or use it. 

Can someone please help? 

Thank you

**Comment by JeremyRand** [comment]
Hi,

Sorry for the delayed reply; things have been busy here.

Make sure you backup your Namecoin profile directory before you try this, but what happens if you run a current Namecoin Core with the `-salvagewallet` command-line paramater?

**Comment by JeremyRand** [comment]
Also, you may find this helpful for dealing with encrypted wallets with PyWallet: https://bitcoin.stackexchange.com/a/9616

**Comment by lukavia** [comment]
I think this is the relevant output:
`2016-04-29 23:06:37 Renamed wallet.dat to wallet.1461971197.bak
2016-04-29 23:06:37 CDBEnv::Salvage: Database salvage found errors, all data may not be recoverable.
2016-04-29 23:06:37 Salvage(aggressive) found 528 records
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey: Error reading wallet database: CPubKey corrupt
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:
2016-04-29 23:06:38 WARNING: CWalletDB::Recover skipping ckey:`

**Comment by JeremyRand** [comment]
@lukavia Did the PyWallet link I provided work any better?  PyWallet should be able to read encrypted keys if you provide the passphrase.

Also pinging @domob1812 , @brandonrobertz , and @ryancdotorg since they've worked with the wallet code.

**Comment by JeremyRand** [comment]
As an aside, because it seems that some people on Twitter are linking to this issue without providing context (or providing incorrect context), it's worth pointing out that it's likely that this issue only affects Namecoin 0.3.x.  Namecoin Core is believed to be unaffected.  Obviously that fact doesn't help recover the OP's wallet, which is why this issue isn't being closed.  But the allegations floating around Twitter that this is an unfixed bug are, AFAICT, probably inaccurate.

(Apologies to OP for cluttering the thread with this, and for the fact that the Twitterverse likes to politicize things.)

**Comment by JeremyRand** [comment]
@lukavia From what I understand, a new wallet.dat was generated when you ran Namecoin Core with -salvagewallet .  Can you try dumping the private keys from that new wallet and see if it has any private keys that you didn't have in your unencrypted backup?

**Comment by JeremyRand** [comment]
Also, please don't tell us what names you own on a public GitHub, but just so that we know how urgent things are, are any of the missing 3 names expiring fairly soon?

**Comment by lukavia** [comment]
Thank you very much for all your efforts. The 3 names in question have more than 34000 blocks to go so there is still time. However due to those problems I've managed to miss renew other names and lost them, so this made me drop this project since it is just too easy to lose your names. However I'll still try to help you resolve this issue. 

For the pywallet: I didn't help. I get this: 
```
Traceback (most recent call last):
  File "/home/ubuntu/tmp/pywallet.py", line 2123, in parse_wallet
    item_callback(type, d)
  File "/home/ubuntu/tmp/pywallet.py", line 2506, in item_callback
    compressed = d['public_key'][0] != '\04'
IndexError: string index out of range
ERROR parsing wallet.dat, type ckey
key data: ckey
key data in hex: 04636b657900
value data in hex: 00
```

I'm currently running namecoin-core with the wallet backup, once it rescans I'll try encrypting the wallet so we can confirm this does not affect namecoin-core.

**Comment by lukavia** [comment]
OK. I can confirm namecoin-core is NOT affected from this bug!

**Comment by lukavia** [comment]
the -salvagewallet run terminates the process. After restarting the core daemon the wallet is completely empty

**Comment by JeremyRand** [comment]
@lukavia Thanks for testing Namecoin Core.

My understanding of how `-salvagewallet` works is that the wallet it creates has no transactions, only keys.  Can you try running Namecoin Core with the `-rescan` command line flag, using the wallet that was created by `-salvagewallet`?  It might take a bit of time to rescan the blockchain (not sure exactly how long, probably somewhere between 5 minutes and 2 hours, but it's been a while since I did it).

Once that finishes, can you check whether any of your names / transactions are present?  (Namecoin Core master branch doesn't have the name GUI merged yet, but the `name_list` RPC call should show any names in the wallet that were detected during the rescan.)

**Comment by JeremyRand** [comment]
(Also, I'm not certain how to deal with that error in PyWallet.  Let's come back to that if the `-rescan` command line flag as described above doesn't help.)

**Comment by lukavia** [comment]
After rescan the problem seems resolved. 
I can unlock my wallet and even managed to renew one address I have missed. 
Thank you very much for all your efforts. 
Too bad I lost to many names to continue with this project. 

Wish you all the best

**Comment by JeremyRand** [comment]
Glad to hear that the problem appears resolved.  Thanks so much for sticking around to help us debug, I really appreciate it.

I'll leave this issue open for the next few days in case any additional trouble is discovered; if not, then I'll close it.

**Comment by lukavia** [comment]
19FP 
I'm posting this in order to confirm my identity to some gracious person how have agreed to restore my domains, which will bring my fate in the project so I can continue to support it.

**Comment by JeremyRand** [comment]
@lukavia Were you able to get your names returned?

**Comment by lukavia** [comment]
Yes, I'm very happy with the outcome. I'm currently looking for a way my home router to resolve .bit address and continuing to play with this project. 
I think we can close this now. 

Thank you very much for all your help.

**Comment by JeremyRand** [comment]
Happy to help; glad to hear that there was a happy ending.
