### ISSUE TITLE
Using systemctl to start will be failed (Result: timeout) 

### ISSUE THREAD

**Issue by NomadThanatos** [namecoin/namecoin-core#90]
I think that loading block index costs too much time and block the main process.

debug.log:

```
namecoin version 0.3.80
Default data directory /home/namecoin/.namecoin
Bound to port 8334
Setup namecoin genesis block 000000000062b72c5e2ceb45fbc8587e807c155b0da735e6483dfba2f0a9c770
Loading addresses...
dbenv.open strLogDir=/home/namecoin/.namecoin/database strErrorFile=/home/namecoin/.namecoin/db.log
Freeing 0 entries in CMapBlockIndex...
Freeing 0 nodes in CNodeList 0x99d100...
ThreadRPCServer started
Loaded 535 addresses
 addresses               313ms
Loading block index...
LoadBlockIndex(): hashBestChain=5b7efa84c1f73afb3ac4  height=282582
```

**Comment by domob1812** [comment]
First of all, the log output indicates that you are using Namecoin 0.3.80.  This repository is for the newer Namecoin Core, which is very probably more performant in almost all aspects (including initial startup).  Second, I think we need more details to debug the problem - what exactly are you trying to do, including any config files or command lines you use.

**Comment by domob1812** [comment]
Closing as obsolete.  Feel free to reopen if the issue still occurs with the latest code (and, especially, not 0.3.80).
