### ISSUE TITLE
Release process changes from upstream

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#91]
This is just a heads up that upstream Bitcoin Core has made major changes to the documentation of their release process.  See https://github.com/bitcoin/bitcoin/pull/7881 .

Let me know if there are any difficult-to-resolve conflicts between the upstream changes and the changes I've implemented for Namecoin Core.  The changes look fairly innocuous to me (mostly formatting), but I only looked briefly.

**Comment by domob1812** [comment]
Thanks.  I will do the next merge next weekend (presumably) and will let you know if I encounter serious issues.

**Comment by domob1812** [comment]
I've pushed the merge - I tried my best to consolidate the changes, but if you have time, please take a look and fix them (if necessary).  Thanks!
