### ISSUE TITLE
Re-enable bip68-112-113-p2p.py

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#94]
We disabled the test bip68-112-113-p2p.py because Namecoin doesn't yet handle BIP9.  See https://github.com/namecoin/namecoin-core/issues/86 .  After BIP9 is enabled on the Namecoin network, we should re-enable that test.

**Comment by domob1812** [comment]
This is fixed now.  While BIP9 has not been activated, at least regtests now activate the corresponding softforks via block height and thus the tests are able to run.
